Update Context Selector Example to reflect lastest Masthead design
patternfly/patternfly-3 pull request #1037
Opened 2018-04-25 15:55 UTC by michael-coker

fixes #1029

## Description
Update context selector snippet to reflect new masthead design.

## Changes
* Update navbar item hover/open state CSS
* remove caret from masthead in context selector snippet

## Link to rawgit and/or image

the bootstrap-select unit test is failing so the build on travis fails. will update this PR once that's fixed.

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2018-05-02 14:20 UTC, mcoker commented
@matthewcarleton added the rawgit test URL.

2018-05-02 14:25 UTC, mcarrano commented
Looks great @michael-coker !

2018-05-02 16:39 UTC, matthewcarleton commented
@michael-coker looks great! The only things I'm seeing is this is inheriting bootstrap selects behaviour of putting focus on the search when the dropdown is active. In our other dropdowns the dropdown remains in focus when active. Should we consider making this more consistent @mcarrano ?

2018-05-02 16:44 UTC, matthewcarleton requested changes
see my comment  ⬆️

2018-05-02 17:14 UTC, mcarrano commented
@matthewcarleton I guess this becomes a question of what's the right thing to do from an accessibility standpoint. I don't see a problem with what's implemented here, but would be interested in hearing thoughts from @jgiardino .

2018-05-02 17:37 UTC, matthewcarleton commented
ya I agree @mcarrano

2018-05-02 18:21 UTC, mcoker commented
@matthewcarleton @mcarrano another discrepancy I just found is the `:focus` state of the context selector has a blue border/outline, and the menus on the right do not. 

The `:focus` state is consistent between all of the masthead dropdown items when you toggle `:focus` in dev tools, however if you do this, you'll see the difference:

1. Click the context selector dropdown twice (open and close it) and move your mouse away - you should see the blue outline/border.
1. Click either the help or user menu the same way (twice to open/close it) and when you move your mouse away, you should not see a blue outline.

However, as mentioned above, toggling the `:focus` state in dev tools creates a blue border/outline for all of those menus.

Not sure why that's happening, but would you like me to look at that as well? If so, those menu links are visually indicated with a light background on `:focus`, which is appearing fine for all of the links. Should they also have a blue border/outline, or should I remove that and just leave the light background as indication that the item has `:focus`?

2018-05-02 19:24 UTC, mcarrano commented
All great questions @michael-coker .  To complicate this further, it behaves differently on different browsers. I use Firefox by default and didn't see this, but I can reproduce on Chrome. In fact for Firefox, I don't really seem to get any visual indication of focus like I do on Chrome. 

I guess that if we can suppress the blue focus rectangle on the context selector, that were be preference as it looks odd in the masthead.

2018-05-02 19:42 UTC, michael-coker commented
@mcarrano ah, good catch! I was only testing in Chrome. The behavior is quite a bit different in Firefox. You can't tab to the help/user menu links in FF, either. @matthewcarleton gave me access to Browserstack and the behavior in IE10/11 and edge is consistent and matches Chrome for the most part (you can tab to all of the menus and the focus state is inicated, though focusing on the context menu has a border/outline and the other links in the masthead do not)

2018-05-02 21:08 UTC, jgiardino commented
@michael-coker For keyboard navigation in FF, I think it follows settings you have defined for your Mac System Preferences > Accessibility > Keyboard. I'm happy to compare what I have with yours if it helps, but that might be what's preventing you from navigating with a keyboard in Firefox.

For showing focus, I do think having some visual indication is important. I don't have a strong preference regarding whether we use our own visual styling or use the method that the browser provides. I think arguments can be made in support for both. 

For keyboard behavior when using the context selector, I was reviewing the different variations on the [bootstrap select test page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-select.html) and there are differences among those variations. For example, the only difference between the Single-Select Dropdown on that test page and the [Dropdown](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/dropdowns.html) (like what we use for the other menus in the masthead) is that focus immediately shifts to the first menu item in the Select menu and focus stays on the toggle in the Dropdown. Other than that, Tab and Arrow keys seem to behave the same. 

But the context selector appears to be based on the Data Live Search variation on the [bootstrap select test page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-select.html). In this example, I can only shift focus to another menu item using Arrow keys. If I hit the Tab key, the menu will collapse and focus will shift to the next item in the masthead.

Since the inconsistencies in keyboard navigation are not based on this implementation of the bootstrap-select component, but are part of the bootstrap-select component itself, I'm hesitant to suggest any changes. If we changed this implementation, would we also update the bootstrap-select component itself? Since this is pf 3, I'm inclined to keep the bootstrap and 3rd party implementations of bootstrap-like components as they currently are, and revisit this interaction pattern as part of pf next.

2018-05-02 22:21 UTC, mcoker commented
Thanks @jgiardino! Other than the inconsistencies mentioned above, everything looks good cross-browser.

2018-05-03 13:55 UTC, matthewcarleton submitted a review, later dismissed

2018-05-03 14:07 UTC, michael-coker commented
@mcarrano @jeff-phillips-18 when one of you have a sec, would you mind reviewing this PR?

2018-05-03 18:25 UTC, michael-coker commented
@jgiardino @srambach @dgutride would one of you mind giving this a review?

2018-05-03 18:37 UTC, mcarrano commented
What did we decide about the issue with the focus state @michael-coker . Are we going to leave as is? I'm OK with that unless there is an easy fix.

2018-05-03 20:08 UTC, michael-coker commented
@mcarrano I was fine with leaving it as is, but I took another look at it and changed the `<a>` links that act as dropdown toggles in the navbar to `<button>`'s instead. Now the menus are all keyboard accessible (except in Safair, but it never worked in safari), and the focus/outline behavior is the same on chrome/opera, and although different from chrome/opera, the same on firefox and all versions of IE. I think that's an improvement. Rebuilt the demo link (https://rawgit.com/michael-coker/patternfly/update-context-selector-masthead-dist/dist/tests/)

2018-05-03 20:13 UTC, jeff-phillips-18 commented on src/less/variables.less
> -@navbar-pf-vertical-active-color:                                   @color-pf-white;
Removing this _could_ be considered a breaking change.

2018-05-03 20:20 UTC, mcoker commented on src/less/variables.less
> -@navbar-pf-vertical-active-color:                                   @color-pf-white;
Ah! Thanks @jeff-phillips-18 this is my first contribution to PF, I appreciate the feedback. Can you clarify what a breaking change would be? I grepped the codebase for that var before committing, but I suppose someone could be using that variable in their own CSS? If so, would it be a better practice to add it back as

```
@navbar-pf-vertical-active-color: @navbar-pf-item-active-color;
```

2018-05-03 20:47 UTC, jeff-phillips-18 commented on src/less/variables.less
> -@navbar-pf-vertical-active-color:                                   @color-pf-white;
Correct. If an adopter is referencing this variable it would break them. Better to leave it and set it as you have above.

2018-05-03 20:57 UTC, mcarrano commented
Looks good @michael-coker . I can see the consistency when tabbing around.

2018-05-03 20:58 UTC, michael-coker commented on src/less/variables.less
> -@navbar-pf-vertical-active-color:                                   @color-pf-white;
@jeff-phillips-18 awesome. Added back and updated the branch.

2018-05-04 11:52 UTC, jeff-phillips-18 approved these changes

2018-05-04 15:08 UTC, merged