fix(treegrid): Refactor the treegrid component
patternfly/patternfly-3 pull request #1054
Opened 2018-05-15 09:06 UTC by dabeng

## Description
This PR is targeted to fix issue #947

## Changes

Just replace the low efficient selector with a higher one

## Link to rawgit and/or image

Feel free to experience the performance difference between the following demos:
- [TreeGrid Table Testing](https://codepen.io/dabeng/pen/xWRXyX)
-  [TreeGrid Table Testing2](https://codepen.io/dabeng/pen/wmopwd)

2018-05-15 15:38 UTC, dgutride submitted a review, later dismissed

2018-05-16 11:04 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-tree-grid.js
> +        parent = $(parent);
I fear applications may be counting on the use of `closest` and not be using unique `data-parent` selectors. Can we add a check for multiple results and if there are multiples revert to using `closest`?

2018-05-17 02:43 UTC, dabeng commented on src/js/patternfly-functions-tree-grid.js
> +        parent = $(parent);
Hi @jeff-phillips-18 . In this sentence, "parent" is just "#id".
`parent = rows.closest(parent);`

2018-05-17 16:15 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-tree-grid.js
> +        parent = $(parent);
not necessarily, it is whatever the `data-parent` attribute is set to. Could be an id, maybe should be and id, but it doesn't _have_ to be an id. There may be applications out there using a selector other than id and that selector might not be unique.

2018-05-18 00:25 UTC, dabeng commented on src/js/patternfly-functions-tree-grid.js
> +        parent = $(parent);
Yes. You are right Jeff :blush:  variable "parent" could be an id but it doesn't have to be an id.

If we review the source code of treegrid table example, we will find that there are two types of “data-parent” attribute as shown below. One is row index(int), the other is row id(string) .

![screenshot from 2018-05-18 07-43-00](https://user-images.githubusercontent.com/5689075/40209868-70e4fa74-5a74-11e8-9187-d35a96555971.png)

So the author of treegrid plugin use the following code block to handle the scenario of row index:

![screenshot from 2018-05-18 08-07-06](https://user-images.githubusercontent.com/5689075/40209922-c375590a-5a74-11e8-80b8-e18dfb42a1c8.png)


and use the following code block to handle the use case of row id:
![screenshot from 2018-05-18 08-08-34](https://user-images.githubusercontent.com/5689075/40209961-f7b08118-5a74-11e8-84cc-b761cb7e2f69.png)

2018-05-18 11:47 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-tree-grid.js
> +        parent = $(parent);
I'm just saying... it used to use `closest`, your change removes that and _expects_ the selector to be unique. _IF_ there are _any_ applications out there already using this but use a selector that is _not_ unique, then this is a breaking change.

If we add a check to ensure the selector is unique (length of 1) and if not revert to using _closest_, then this is _not_ a breaking change.

2018-05-18 11:49 UTC, jeff-phillips-18 requested changes
Convinced myself that we should add the check :wink

2018-05-22 17:09 UTC, skateman commented on src/js/patternfly-functions-tree-grid.js
> +        parent = $(parent);
I agree with @jeff-phillips-18

2018-05-23 23:08 UTC, dabeng commented
Hi @jeff-phillips-18 I have added check according to your advice.

2018-05-24 10:49 UTC, jeff-phillips-18 requested changes

2018-05-24 10:49 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-tree-grid.js
> +        parent = parent.charAt(0) === '#' ? $(parent) : rows.closest(parent);
non-id selectors can also have just a single result which would not require the `closest` call. I suggest we only use the `closest` call if the selector returns multiple elements:

```
parent = $(parent);
if (parent.length > 1) {
  parent = rows.closest(parent);
}
```

May cause an extra lookup but only if the application did not use a unique selector.

2018-05-30 06:18 UTC, dabeng commented
Hi @jeff-phillips-18 I have updated PR according to your advice.

2018-05-30 10:43 UTC, jeff-phillips-18 approved these changes

2018-06-22 11:06 UTC, dgutride approved these changes

2018-06-22 11:06 UTC, merged