feat(message-dialog): Add the message-dialog pattern
patternfly/patternfly-3 pull request #1074
Opened 2018-06-13 11:42 UTC by michaelkro

## Description
The message dialog pattern is built on `modal`, and consequently, almost all of the introduced CSS are overrides to `modal` styles dictated by [the specs outlined here](https://github.com/patternfly/patternfly-design/issues/632#issuecomment-396402810)

**Notes**
1. SASS/LESS nesting is used here to scope the `modal` overrides to `.message-dialog-pf`
2. Test examples based on [original samples](https://github.com/patternfly/patternfly-react/issues/360#issuecomment-392789901)
3. Closes https://github.com/patternfly/patternfly/issues/1064

## Link to rawgit

[rawgit](https://rawgit.com/michaelkro/patternfly/message-dialog-rawgit/message-dialog-dist/dist/tests/message-dialogs.html)

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2018-06-13 11:45 UTC, michaelkro commented
@serenamarie125

2018-06-13 14:38 UTC, serenamarie125 commented
@michaelkro a few requests:

1. Clicking the primary action button on all of the examples should close the dialog
1. Autofocus on the primary button for Non Destructive, Message, Success & Min Height Dialog examples
1. Autofocus on the secondary button for Error, Delete Confirmation, Warning, Question examples
1. Once a button has focus, tab should traverse between buttons.  But disregard the "x"

2018-06-13 15:12 UTC, mcarrano commented
@matthewcarleton @deernano I tagged you guys to also take a look at this for PF Core contribution. We don't yet have an approved design, but just want to make sure there are no disconnects with current direction. My only question is around the recommended button lables, i.e. "Close" vs. "OK" for acknowledgement. @deernano please verify.

2018-06-14 08:12 UTC, deernano commented
@mcarrano  I would prefer ok than close. Ok is more like the action after the user is acknowledged.

2018-06-14 08:18 UTC, deernano submitted a review, later dismissed
Looks good to me

2018-06-14 10:21 UTC, jeff-phillips-18 commented
I believe initial focus should be on the primary button.
Something other that the buttons is in the tab order, but I'm not sure what.

2018-06-14 10:55 UTC, jeff-phillips-18 reviewed
In general, I question why the message dialog has different margins/colors from modal. I see the spec you are working from specifies these settings but I'm not sure they need to vary from the existing modal settings. @jennyhaines ?

2018-06-14 10:55 UTC, jeff-phillips-18 commented on src/less/modals.less
> +    padding-right: 18px;
padding-right should already be 18px.

2018-06-14 10:55 UTC, jeff-phillips-18 commented on src/less/modals.less
> +  }
if we set a line-height of 20px here, we could remove the height, align-items, and padding top/bottom from the .modal-header settings.

2018-06-14 10:55 UTC, jeff-phillips-18 commented on src/less/modals.less
> +    }
The colors here should us colors from the palette and use variables. Is there a reason why message-dialog is different from modal here?

2018-06-14 10:55 UTC, jeff-phillips-18 commented on src/less/modals.less
> +    color: @color-pf-black-500;
We use @color-pf-black-700 for the alert, should this be the same?

2018-06-14 12:06 UTC, matthewcarleton commented on src/less/modals.less
> +    padding-right: 18px;
There are alot of things here that I don't think are necessary. We should not apply height here. I'm curious why we are reapply any of this when the modal already has it? Shouldn't the styles be consistent with what we already have?

2018-06-14 12:10 UTC, matthewcarleton commented on src/less/modals.less
> +    flex-direction: column;
I would remove flex from here and add `line-height:0;`

2018-06-14 12:12 UTC, matthewcarleton commented on src/sass/converted/patternfly/_modals.scss
> +      content: none;
what is the purpose of this?

2018-06-14 12:14 UTC, matthewcarleton commented on src/sass/converted/patternfly/_modals.scss
> +  .modal-title {
I don't believe either of these are necessary.

2018-06-14 12:16 UTC, matthewcarleton commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +    <div class="modal-content message-dialog-pf">
`.message-dialog-pf` should be with the `.message-dialog`

2018-06-14 12:19 UTC, matthewcarleton commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" tabindex="-1">
I'm not sure about the `aria-hidden="true"` and `tabindex="-1"` here. what are the reasons for hiding this from screen readers?

2018-06-14 12:20 UTC, matthewcarleton commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
This should be wrapped in a`<p>`

2018-06-14 12:20 UTC, matthewcarleton commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +            Main dialog text
this should use a heading

2018-06-14 12:24 UTC, matthewcarleton commented
@michaelkro thanks for doing this! I've left some comments. 

One overall question I have is why we aren't using the styles that we have for the modal already? Are they different for the message dialog? If so, I think we should consider realigning the design to make it more consistent.

@serenamarie125 can you explain why the desired outcome is not being able to tab to the "x"? I think that's what you requested Serena unless I misinterpreted it.

2018-06-15 01:33 UTC, serenamarie125 commented
@matthewcarleton that was my request (not tabbing to the "X") - I thought we did the same with the wizard but I could be wrong.  If the "X" is a short cut for the "Cancel"/"Close/OK" button, I'm not sure why it would be included in the tab order, but happy to defer on this !

2018-06-15 01:35 UTC, serenamarie125 commented
@matthewcarleton did you see the specs which are referenced in the initial description?  Jenny produced these a few days ago, as part of the new pattern designs.

2018-06-15 12:02 UTC, michaelkro commented on src/sass/converted/patternfly/_modals.scss
> +      content: none;
The pseudo-elements were interfering with my `justify-content: space-between`

I was definitely a little iffy about this, but not sure how to push the header contents to the ends of the div.  Any suggestions to do this without removing the elements?  I assume they are there for a reason lol

2018-06-15 12:04 UTC, michaelkro commented
I've updated the following
* CSS/HTML cleanup
* Put the header close button back into tab sequence

Will wait for further direction regarding `modal` spacing/color overrides

2018-06-15 12:10 UTC, michaelkro commented
btw, thank you all for the detailed reviews, I appreciate it so much!!!

2018-06-15 16:34 UTC, matthewcarleton commented
@michaelkro I have spoken to @mcarrano and @jgiardino this morning about this and we are all on the same page that the styles that are over writing the default styles for the modal should be removed. I can comment further on the code if you'd like or if you want to chat quickly just let me know. 
@serenamarie125 I also talked to @jgiardino about the "X" and she agrees that it should receive focus.

2018-06-18 12:50 UTC, jeff-phillips-18 commented
Can you update the rawgit link?

2018-06-18 12:51 UTC, michaelkro commented
I just did @jeff-phillips-18 :)

2018-06-18 13:15 UTC, jeff-phillips-18 commented
I liked the message title and body layout before. It kept things centered with the icon when there was little text or top justified if there was enough text.

Seems to me the `Message dialog title` text should be bold.

2018-06-18 13:31 UTC, matthewcarleton commented on src/sass/converted/rcue/_modals.scss
> +  line-height: 0;
you should be able to remove this now. It is using the line-height from the .pf-icon class.

2018-06-18 13:32 UTC, matthewcarleton commented on src/less/modals.less
> +  line-height: 0;
you should be able to remove this now. It is using the line-height from the .pf-icon class.

2018-06-18 13:49 UTC, michaelkro commented
@jeff-phillips-18 are you referring to the primary text, or the modal header title? (for boldness)

2018-06-18 14:02 UTC, jeff-phillips-18 commented
The primary text

2018-06-18 14:06 UTC, jgiardino commented
I'm not sure that text should be bold.

Here are two variations, one with bold, one without, of how I imagine text could be defined in these dialgos. I am making an assumption that the bulk of the message is in the first paragraph with larger text, and that the smaller text only really displays if supplemental text is necessary. But these assumptions could be totally wrong. 

![image](https://user-images.githubusercontent.com/21063328/41540591-93984c7e-72de-11e8-9369-b87ffd46a433.png)

![image](https://user-images.githubusercontent.com/21063328/41540625-9bf7ffc2-72de-11e8-85f1-8f6207df36d0.png)

2018-06-18 14:26 UTC, mcarrano commented
The intended design is outlined here https://github.com/patternfly/patternfly-design/issues/632 Let's try to remain consistent with that (other than following the default modal styling as discussed above). The summary text is not bold.

2018-06-18 14:46 UTC, jeff-phillips-18 commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +        <div class="message-dialog-pf-text">
`message-dialog-pf-text` is no longer defined. Do we need this div at all?

2018-06-18 14:48 UTC, michaelkro commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +        <div class="message-dialog-pf-text">
It's for the `flex` layout of `message-dialog-pf-body`, to keep the primary and secondary text nodes grouped as a single flex child

2018-06-18 14:51 UTC, jeff-phillips-18 commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +        <div class="message-dialog-pf-text">
OK, right. But we can remove that class

2018-06-18 14:53 UTC, michaelkro commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +        <div class="message-dialog-pf-text">
Ok, yes, sorry, force of habit.

Taking that out now!

2018-06-18 14:58 UTC, jeff-phillips-18 submitted a review, later dismissed

2018-06-18 16:07 UTC, matthewcarleton commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +  <div class="modal-dialog">
I wonder if it makes more sense to have the `.message-dialog-pf` here and use that to target the `.modal-body` and the `.pficon` rather than adding classes for each. I think from a users perspective this will be easier to implement. @jeff-phillips-18 @jgiardino what do you think?

2018-06-18 16:52 UTC, jeff-phillips-18 commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +  <div class="modal-dialog">
Not sure we can specify just .pficon and assume it is the dialog icon. But I could agree with this for the `.modal-body`.

2018-06-18 16:58 UTC, matthewcarleton commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +  <div class="modal-dialog">
true. what about `.message-dialog-pf .modal-body .pficon` ? I like the idea of reducing the amount of unique markup for the modal.

2018-06-18 17:01 UTC, jeff-phillips-18 commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +  <div class="modal-dialog">
My concern is folks adding icons in their message text. Might be unlikely. May also need to account for `.fa` as well though.

2018-06-18 17:09 UTC, matthewcarleton commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +  <div class="modal-dialog">
ya that's a good point. I'd be ok with leaving the icon class. But also adding it to the main wrap and removing it from the modal-body. @michaelkro are you ok with this approach?

2018-06-18 17:13 UTC, michaelkro commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +  <div class="modal-dialog">
Sure!  I think I am picking up what you guys are putting down...  I'll push a commit and see if I get it right lol

2018-06-18 20:22 UTC, jeff-phillips-18 requested changes

2018-06-18 20:22 UTC, jeff-phillips-18 commented on src/less/modals.less
> +  &-icon {
I think this should be: 
```
  .fa,
  .pficon {
      font-size: 30px;
      margin-right: 15px;
  }
```

2018-06-18 20:22 UTC, jeff-phillips-18 commented on tests/pages/_includes/widgets/communication/message-dialog-delete-confirmation.html
> +        <span aria-hidden="true" class="pficon pficon-error-circle-o message-dialog-pf-icon"></span>
No longer need `message-dialog-pf-icon`

2018-06-18 20:23 UTC, michaelkro commented on src/less/modals.less
> +  &-icon {
I think that will interfere with the header close icon though, right?

2018-06-18 20:26 UTC, jeff-phillips-18 commented on src/less/modals.less
> +  &-icon {
yeah, it should be under `.modal-body`

2018-06-18 20:44 UTC, jeff-phillips-18 approved these changes

2018-06-18 23:52 UTC, serenamarie125 approved these changes
@michaelkro LGTM thanks for doing this!

2018-06-19 12:18 UTC, merged