fix(semantic): bump minimum version for semantic release
patternfly/patternfly-3 pull request #1098
Opened 2018-07-18 22:07 UTC by mindreeper2420

## Description
This PR bumps the minimum version of the Semantic Release package. This is due to the error with incorrect HTML rendering in the automated release messages.

This issue was fixed in the package update for Semantic Release from September 2017.

The PR addresses issue https://github.com/patternfly/patternfly/issues/876

A matching PR has been filed to the PatternFly Release Repo: https://github.com/patternfly/patternfly-eng-release/pull/87

## Changes

Write a list of changes the PR introduces

* Update Semantic Release package from a minimum of 6.3.6 to 15.0.0.

2018-07-20 15:31 UTC, dlabrecq requested changes

2018-07-20 15:31 UTC, dlabrecq commented on package.json
> +    "semantic-release": "semantic-release pre && npm prepare && semantic-release post",
I don't believe these commands will publish a package. 

1. The `pre/post` commands don't appear to be valid with semantic-release 15.x
2. `npm prepare` isn't a valid option for `npm`
3. The latest semantic version requires node 8+

2018-07-20 18:36 UTC, mindreeper2420 commented on package.json
> +    "semantic-release": "semantic-release pre && npm prepare && semantic-release post",
@dlabrecq I have another PR (https://github.com/patternfly/patternfly/pull/1100), which you commented on, that upgrades to node 8+. Would it make more sense to combine the two, or just have the node update merged first?

Regarding the `pre/post` commands, I've changed them over to `prepare/publish`, per the semantic release docs (https://github.com/semantic-release/npm#prepare).

2018-07-23 12:59 UTC, dlabrecq commented
Unless the node 8 PR is committed first, this PR will not build as is. 

Note that semantic release is all done via configuration now. Where are you referencing the prepare/publish commands from?

2018-07-24 18:42 UTC, mindreeper2420 commented
@dlabrecq I updated the node 8 PR per your comments. Regarding the commands, the `prepare/publish` came from the Semantic Release documentation and, I believe, are included commands in the package.

2018-07-24 21:26 UTC, dlabrecq commented
Both prepare/publish are not valid via the command line. (I say that because I just implemented the latest semantic release for patternfly-ng.) However, there are prepare/publish plugins defined in package.json. 

For reference, you can look at the package.json of patternfly-ng and patternfly-next. ~~We'll also need to modify travis.yml to call semantic release directly instead of using the patternfly-eng-release script because we no longer call npm publish directly.~~

~~You might also consider testing this with a dummy npm package, run via your own fork? As with patternfly-ng and patternfly-next, it took a few iterations to nail down.~~

2018-07-24 21:43 UTC, dlabrecq commented
One more thing to note is that the Travis build also updates the package.json version number committed to master-dist -- this is required for bower installs.

Currently, we use the old semantic release pre/post commands to determine the package.json version. Then, that change is committed to master-dist for bower installs.

Now that the semantic release pre/post commands are no longer available, we need a new way to do this. Thinking we might be able to commit package.json after the semantic release?

2018-07-26 14:31 UTC, dlabrecq requested changes

2018-07-26 14:31 UTC, dlabrecq commented on package.json
> +    "semantic-release": "semantic-release prepare && npm publish && semantic-release publish",
I took a closer look at the available semantic-release commands. The prepare/publish args are not valid (as is) via the command line, but --prepare and --publish are.

2018-07-26 14:31 UTC, dlabrecq commented on package.json
> +    "semantic-release-prepare": "semantic-release prepare",
We can delete these two lines as they are unused. Or, change the semantic-release target to use them (i.e., using npm-run-all)?

2018-07-30 13:58 UTC, mindreeper2420 commented on package.json
> +    "semantic-release": "semantic-release prepare && npm publish && semantic-release publish",
I updated the script to use `semantic-release --prepare` and `semantic-release --publish`, but I can't run them locally without errors. Is that expected?

2018-07-31 19:57 UTC, dlabrecq approved these changes
Looks good to me.

2018-08-01 11:19 UTC, jeff-phillips-18 approved these changes

2018-08-01 17:15 UTC, merged