feat(node): Update Node to v8 LTS
patternfly/patternfly-3 pull request #1100
Opened 2018-07-19 00:18 UTC by mindreeper2420

## Description
This PR updates the required version of NodeJS from v6.x to v8.x (LTS). By doing so, we move out of using a version of Node that is in Maintenance support (https://github.com/nodejs/Release#release-schedule).

Issue https://github.com/patternfly/patternfly/issues/1025

## Changes

* Update required NodeJS from v6.x to v8.x
* Update `.travis.yml` to use v8 on build
* Replace `package-lock.json` with `npm-shrinkwrap.json` (see https://docs.npmjs.com/cli/shrinkwrap).

2018-07-19 20:17 UTC, dlabrecq requested changes
Instead of committing the npm-shrinkwrap.json file, commit package-lock.json. That will ensure that the build is generated with the same version you tested.

The shrinkwrap file is currently generated during the Travis build and committed to master-dist for npm publishing and bower installs.

2018-07-24 22:12 UTC, dlabrecq approved these changes

2018-07-25 11:20 UTC, jeff-phillips-18 approved these changes

2018-07-25 11:21 UTC, merged

2018-07-31 15:43 UTC, martinpovolny commented
> This PR updates the required version of NodeJS from v6.x to v8.x

This seems to be a fairly big change for a minor release of PF :-(