chore(vertical-nav): Provide new option to PF vertical navigation
patternfly/patternfly-3 pull request #1109
Opened 2018-07-26 03:15 UTC by dabeng

## Description
This PR is targeted to issue #727.

In this PR, we expose new options - rememberOpenState and storage to fulfill the demands mentioned on the issue #727.

## Link to rawgit and/or image

Here's the [demo page](https://rawgit.com/dabeng/patternfly/ls-option-dist/dist/tests/). Feel free to access the following eamples:
![image](https://user-images.githubusercontent.com/5689075/43239188-fff1ef80-90c3-11e8-97f5-1d78c287622e.png)

@dgutride @amarie401 Could you review this PR when you have time :blush:

2018-07-26 10:41 UTC, jeff-phillips-18 commented
I believe we can leave the set of test pages as is as it only serves to confuse with so many options that are not really visually different. I would actually prefer all the existing vertical nav test pages use the no storage option so that they always start in the initial (non-collapsed) state.

2018-07-27 02:21 UTC, dabeng commented
Hi @jeff-phillips-18 . Do you mean that we should abandon `vertical-navigation-primary-only-no-cache.html` and `vertical-navigation-primary-only-sessionstorage.html`

2018-07-27 10:52 UTC, jeff-phillips-18 commented
Yes. I don't feel those are necessary as test pages. However, it would be good to set `rememberOpenState` to false in the current vertical nav test pages.

2018-07-27 10:58 UTC, jeff-phillips-18 commented
This should be a `feat` as it adds a feature.

2018-07-30 03:41 UTC, dabeng commented
Thanks a lot for your advice. @jeff-phillips-18  I have refactored the PR.

2018-07-30 10:40 UTC, jeff-phillips-18 requested changes

2018-07-30 10:40 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-vertical-nav.js
> +        rememberOpenState: false,
This needs to be initialized to true so that it doesn't break existing uses.

2018-07-31 02:32 UTC, dabeng commented on src/js/patternfly-functions-vertical-nav.js
> +        rememberOpenState: false,
ok. done

2018-07-31 10:33 UTC, jeff-phillips-18 approved these changes
I would still like to see the test pages set the rememberOpenState option to false, but I'm OK with keeping them as is as well.

2018-07-31 12:44 UTC, dgutride approved these changes

2018-07-31 12:44 UTC, merged