fix(blank slate): secondary action buttons do not align properly
patternfly/patternfly-3 pull request #1117
Opened 2018-08-02 10:36 UTC by dabeng

## Description
This PR is targeted to fix issue #907 .

@LHinson @dgutride @mcarrano   Could you review this PR whenever you got chance ?

## Changes

I followed the design doc provided by @nding-anges and added two new blank slate examples on testing page.

## Link to rawgit and/or image

Here's the [demo page](https://rawgit.com/dabeng/patternfly/empty-state-dist/dist/tests/blank-slate.html).

2018-08-07 17:11 UTC, dgutride submitted a review, later dismissed

2018-08-07 17:11 UTC, dgutride commented
Looks good from functionality perspective - could use a css review, though.

2018-08-07 20:41 UTC, mcarrano submitted a review, later dismissed
Looks good to me.

2018-08-08 11:50 UTC, jeff-phillips-18 requested changes

2018-08-08 11:50 UTC, jeff-phillips-18 commented on src/less/blank-slate.less
> +        background-color: @gray-light;
This should be a color from the patternfly color palette. Likely either `@color-pf-black-400` or `@color-pf-black-500`

2018-08-21 14:18 UTC, jeff-phillips-18 approved these changes

2018-08-21 14:19 UTC, merged