Login Basic Alert page has been created and aligns with styles from design specs
patternfly/patternfly-3 pull request #1129
Opened 2018-08-16 18:23 UTC by christiemolloy

fix #1125

## Description

Needed to fix the log in screen implementation (styles to align with the login alert page). 

## Changes

* Created login-basic-alert.html
* added alert component 
* 100px padding-bottom added to the footer
* text-danger added below form inputs with red color 
*padding added to the top of the page

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2018-08-17 13:31 UTC, matthewcarleton commented
Thanks @christiemolloy this is looking good. We can take a look at the error. It's likely from your json file.

2018-08-17 16:42 UTC, jeff-phillips-18 requested changes

2018-08-17 16:42 UTC, jeff-phillips-18 commented on tests/pages/_includes/widgets/framework/login-basic-alert.html
> +
Might be better to add an variable to login-basic.html so as not to repeat all that content. Something like
```
<div class="login-pf-page">

{% if page.login-alert %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">
            {% include widgets/communication/alert-danger.html %}
        </div>  
    </div>
</div>
{% endif %}

...
```

Then in the header of login-basic-alert.html:
```
login-alert: true
```

2018-08-17 16:42 UTC, jeff-phillips-18 commented on src/less/login.less
> +  // padding-bottom: @login-pf-page-padding-bottom;
remove commented out code

2018-08-17 16:42 UTC, jeff-phillips-18 commented on src/less/login.less
> +    h1 {
why remove the `p` ? Any risk of breaking existing uses?

2018-08-17 16:58 UTC, matthewcarleton commented on src/less/login.less
> +    h1 {
hey @jeff-phillips-18 having all the paragraphs centre aligned is too specific based on the design. There is a helper class in Bootstrap that can be used for text that needs to be centre aligned.

2018-08-17 17:11 UTC, jeff-phillips-18 commented on src/less/login.less
> +    h1 {
OK, thanks.

2018-08-17 17:14 UTC, christiemolloy commented on tests/pages/_includes/widgets/framework/login-basic-alert.html
> +
okay sounds good. will update

2018-08-17 17:14 UTC, christiemolloy commented on src/less/login.less
> +  // padding-bottom: @login-pf-page-padding-bottom;
yes

2018-08-20 13:41 UTC, christiemolloy commented
changes fixed, @jeff-phillips-18 @matthewcarleton

2018-08-20 14:11 UTC, matthewcarleton submitted a review, later dismissed
This looks good, thanks!

2018-08-20 14:18 UTC, jeff-phillips-18 commented on tests/pages/login-basic.html
> +
no need to modify this file

2018-08-20 14:19 UTC, jeff-phillips-18 submitted a review, later dismissed
LGTM, just the one nit. Thanks for updating!

2018-08-20 16:11 UTC, jeff-phillips-18 approved these changes

2018-08-20 16:12 UTC, merged