Make donut chart title consistent between Firefox/Chromium
patternfly/patternfly-3 pull request #1177
Opened 2019-06-11 22:07 UTC by ddelabru

## Description
This PR modifies the SVG styling of Patternfly donut chart titles slightly to use the `y` attribute instead of `dy`, because Firefox treats `dy` on `tspan` elements differently than Chromium.

This PR is intended to address https://github.com/patternfly/patternfly/issues/1168

## Changes

* `<tspan>` elements of the donut chart use the `y` attribute in place of `dy`

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [x] **Cross browser**: works in Chrome
- [x] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2019-06-11 22:12 UTC, ddelabru commented
The unit test that failed appears to be something to do with Bootstrap switches, not sure my commit has anything to do with that. (I had trouble running the test suite locally.)

2019-06-12 11:51 UTC, ddelabru commented
Amended my commit to make the same change to the utilization chart test pages.

2019-06-13 12:27 UTC, ddelabru commented
Finally noticed the commit message guidelines and amended my commit to adhere to them.

2019-06-13 15:02 UTC, redallen requested changes

2019-06-13 15:02 UTC, redallen commented on tests/unit/bootstrap-switch.spec.js
> -    var onButton = $('.btn-group:first button[data-switch-value="true"]');
Can you revert changes to this file or bump our version of Karma to whatever you use locally to get these to pass? Our `grunt karma` now fails with:
```
PhantomJS 2.1.1 (Linux 0.0.0) bootstrap switch test suite should toggle the first switch to ON FAILED
	Expected ({ 0: HTMLNode, length: 1, prevObject: ({ 0: HTMLNode, length: 1, prevObject: ({ 0: HTMLNode, length: 1 }) }) }) to have class 'bootstrap-switch-on'.
	tests/unit/bootstrap-switch.spec.js:39:34
```

Thanks!

2019-06-13 15:20 UTC, ddelabru commented on tests/unit/bootstrap-switch.spec.js
> -    var onButton = $('.btn-group:first button[data-switch-value="true"]');
Accidentally brought this in from another branch where I was attempting to fix the failing unit test. I've reverted the change now.

2019-06-13 19:51 UTC, ddelabru commented
@redallen As requested, I've added the bootstrap-switch dependency version fix to this PR.

2019-06-14 12:55 UTC, redallen approved these changes

2019-06-14 12:55 UTC, merged

2019-06-14 13:15 UTC, patternfly-build commented
:tada: This PR is included in version 3.59.2 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/v3.59.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/patternfly)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: