Wizard
patternfly/patternfly-3 pull request #474
Opened 2016-09-16 19:25 UTC by jgiardino

## Description
Includes functionality to navigate between pages in the wizard, with updates based on feedback from Dan and Patrick.

Also sets the height so that it is consistent from screen to screen, instead of changing size based on the screen contents.

NOTE: Only the first button shows a wizard with functional navigation. The last two buttons are intended to show examples of transient screens (loading and processing).

https://patternfly.atlassian.net/browse/PTNFLY-1827

## Changes

- Included javascript to implement navigation functionality in wizard.html
- Set pointer-events: none for disabled buttons in buttons.less. This is intended to actually disable click events for the disabled buttons. But this also means the mouse cursor can't change to the one that is currently specified. The alternative is to include extra javascript to detect if the buttons is disabled.
- On the final screen, I made the Back button disabled. This currently shows as enabled, but that seemed incorrect in this case.
- Modified html, css and js to set the height. The height is sized to fit the height of the window, with a maximum height of 900px.
- Modified the width for the wizard modal to be slightly different than the regular modal, since the form layout was not responding well to the 600px width that is applied when the viewport is >768 and <992. For this case, the wizard modal is full width (minus some spacing around the edges). I did adjust the width of the sidebar when the viewport is < 992 to provide more space to the form.

## Link to rawgit and/or image

Here is a [link to the Wizard on rawgit](https://rawgit.com/jgiardino/patternfly/Wizard-dist/dist/tests/wizard.html)

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2016-09-16 19:27 UTC, jgiardino commented
@kybaker Can you please review the visual styling of the wizard and provide any comments if updates are needed?
https://rawgit.com/jgiardino/patternfly/Wizard-dist/dist/tests/wizard.html

2016-09-19 17:17 UTC, dgutride commented
This looks good from my end, I ran in browserstack in all of the checklist browsers.  I think all of the changes from the previous review were made - @dlabrecq or @andresgalante  - can you guys review?

2016-09-20 11:35 UTC, dlabrecq commented on tests/pages/_includes/widgets/communication/wizard.html
> +      var sidebarwidth = $(self.modal + " .wizard-pf-sidebar").outerWidth() + "px";
Just a nit, but variables will need to be located at the top of each function. When jslint is enabled (soon), it will complain.

2016-09-20 11:36 UTC, dlabrecq commented on tests/pages/_includes/widgets/communication/wizard.html
> +    this.wizardContents = function(){
Just a nit, but will need a space between "()" and "{". When jslint is enabled (soon), it will complain.

2016-09-20 11:41 UTC, dlabrecq commented on tests/pages/_includes/widgets/communication/wizard.html
> +  var wizard = function(id) {
I think this code looks great. Nice job! 

Now we can potentially reuse this code to show additional examples in the same page. For anyone copying this code, there will be less chance of global variable and function name collisions.

2016-09-20 11:46 UTC, dlabrecq commented on tests/pages/_includes/widgets/communication/wizard.html
> +    this.wizardTabGroup = function(){
Prefer function names like updateTabGroup, updateActiveTab, and upadateVisibleContents, instead of wizardTabGroup, wizardTab and wizardContents. I don't feel strongly about it (could leave it as is), but believe descriptive names would help make it clear what each function does?

2016-09-20 11:55 UTC, dlabrecq requested changes

2016-09-20 18:34 UTC, dlabrecq approved these changes

2016-09-20 19:02 UTC, dlabrecq commented
The code looks good, but the Travis build failed. Looked at the log, but don't understand why, yet.

2016-09-20 19:04 UTC, dgutride commented
@dlabrecq  - I looked at Travis also and ran that step locally with no issues.  Seems to be a dependency is out of whack somewhere.  The same failure happened with June's PR also.

2016-09-21 12:36 UTC, merged