Datatables.net
patternfly/patternfly-3 pull request #501
Opened 2016-10-06 14:47 UTC by rhwood

## Description
Use the ```datatables.net``` package instead of the ```datatables``` package for [Datatables](http://datatables.net), since all installations instructions for Datatables use the ```datatables.net``` package.

## Changes

* Use ```datatables.net``` in Bower and NPM
* Use Datatables Buttons extension instead of the (deprecated) Datatables Colvis extension
* Provide default CSS for Datatables Buttons including the Datatables Colvis Button menu

## Link to rawgit and/or image

This is an image:

![Table with one column hidden](https://cloud.githubusercontent.com/assets/297232/19157072/1583ac8a-8bb2-11e6-959e-4f4492636fde.png)

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2016-10-06 14:52 UTC, dtaylor113 commented
Hi, so this doesn't work in IE?

2016-10-06 15:06 UTC, rhwood commented
It's just not tested yet, and is not known to not work.

2016-10-06 16:17 UTC, bleathem commented
This is great, thanks for the PR @rhwood!  Your changes look reasonable to me.

@dlabrecq is leading our datatables.net implementation atm, we'll wait for his review before merging.

2016-10-06 16:33 UTC, rhwood commented
@dtaylor113 I've tested this on IE 11 running in Edge (default), 10, and 9 emulation modes without issue. I've only marked it as working in IE 11.

2016-10-06 18:14 UTC, dlabrecq requested changes

2016-10-06 18:14 UTC, dlabrecq commented on src/less/datatables.less
> +  .dt-buttons {
Do we want all .dt-buttons positioned absolutely or only .dt-button.buttons-columnVisibility?

2016-10-06 18:14 UTC, dlabrecq commented on karma.conf.js
> +      'node_modules/datatables.net/js/jquery.dataTables.js',
Yes! I recently changed the same line in my own code to use datatables.net.

2016-10-06 18:14 UTC, dlabrecq commented on QUICKSTART.md
> +        <script src="bower_components/datatables.net-colreorder/js/dataTables.colReorder.js"></script>
@bleathem @LHinson I don't know that we want to add this to our quick start? The functionality to hide/show columns is not an officially supported design pattern.

I was thinking this example could be removed after the feature branch is finally merged?

2016-10-06 18:14 UTC, dlabrecq commented on bower.json
> +    "datatables.net-buttons-bs": "~1.2.2",
@bleathem Do we want to introduce new dependencies for features that have no design pattern?

2016-10-06 18:14 UTC, dlabrecq commented on src/less/datatables.less
> -.ColVis_Button {
@bleathem @andresgalante Does the removal of these classes imply a major version number bump? Should we leave the old classes as is and somehow mark them as deprecated?

I don't know that the DataTable was officially supported, but thought to ask in case someone may be using these classes?

2016-10-06 18:44 UTC, rhwood commented on src/less/datatables.less
> +  .dt-buttons {
Datatables allows a buttons div with the class .dt-buttons to be created using the dom option when creating a table object where all buttons tied to the table are located. Absolutely positioning the button group does appear to match the [table view](https://www.patternfly.org/pattern-library/content-views/table-view/#_) design.

2016-10-06 18:48 UTC, rhwood commented on src/less/datatables.less
> -.ColVis_Button {
These classes support an object (the ColVis extension) that requires the datatables package (but not the datatables.net package). The ColVis extension is apparently no longer being maintained with the recommendation that it be replaced with the DataTables column visibility button.

I've had problems mixing packages that require datatables and packages that require datatables.net in the same app, since they fight each other.

2016-10-06 21:22 UTC, dlabrecq commented on src/less/datatables.less
> +  .dt-buttons {
Ok, the absolute position seems fine. Although, the toolbar design is a little different than what datatables.net can provide via this mechanism (e.g., I don't know that it can be used to create a kebab)? The design pattern has (optional) action buttons and kebabs on the top while filter results and selected rows text appear below.

2016-10-06 21:39 UTC, rhwood commented on src/less/datatables.less
> +  .dt-buttons {
Are those showing a button within a button? What's the code that was used (they do need to be spaced apart, but also should not be doubly wrapped)?

2016-10-12 16:15 UTC, bleathem commented on bower.json
> +    "datatables.net-buttons-bs": "~1.2.2",
We don't want to introduce these dependencies, no.  We could consume the dependencies in our example via CDN, and users could add dependencies to their own apps if they want the functionality.

2016-10-12 16:18 UTC, bleathem commented on QUICKSTART.md
> +        <script src="bower_components/datatables.net-colreorder/js/dataTables.colReorder.js"></script>
Agreed we should consider how this functionality can be incorporated into our pattern from a design perspective.

@LHinson do we have any design stories in the pipeline to address column re-ordering?

2016-10-12 16:20 UTC, bleathem commented on src/less/datatables.less
> +  .dt-buttons {
The divergence of the patternfly patternfly toolbar design and the datatbles.net toolbar implementation is unfortunate.  @LHinson can I suggest a design story to consider if the two approaches can be better aligned?

2016-10-12 17:41 UTC, dlabrecq commented on src/less/datatables.less
> +  .dt-buttons {
@bleathem @LHinson FYI... The DataTables.net has its own, simple toolbar for placing its pre-canned buttons and filter input elements. It's located similarly, but the Patternfly toolbar layout is far more complex with a custom filter, multiple rows etc. Therefore, we just droped-in our own HTML from the existing toolbar examples (i.e., for the feature branch).

Note that we can still create buttons to control DataTables.net features, so using the pre-canned buttons isn't absolutely necessary. We can still show/hide columns within our own toolbar via the DataTables API.

I don't know that we want to make the pre-canned DataTables.net buttons work with our custom toolbar? Although, a design pattern would help. We may not want to use a button to hide/show columns at all?

2016-10-13 13:37 UTC, bleathem commented on src/less/datatables.less
> -.ColVis_Button {
We shouldn't build further on these classes, but we shouldn't remove them either in case a downstream user is consuming them.  We can mark them for removal in PF 4.

2016-10-13 14:05 UTC, bleathem commented on src/less/datatables.less
> +  .dt-buttons {
@LHinson reminded me that we have a design constraint to co-ordinate the toolbars amongst our various patterns (eg. list view, toolbar, table view).  This rules out using the datatables.net toolbar.  Neither do I see any need to support the datatables.net buttons in our toolbar.

2016-10-13 14:10 UTC, bleathem commented on QUICKSTART.md
> +        <script src="bower_components/datatables.net-colreorder/js/dataTables.colReorder.js"></script>
We are tracking the column visibility with this story:
https://patternfly.atlassian.net/browse/PTNFLY-1489

2016-10-13 16:02 UTC, bleathem commented
Thanks again for taking the time to prepare and submit this PR @rhwood.  

We have made a design decision to use our own [custom toolbar](http://www.patternfly.org/pattern-library/forms-and-controls/toolbar) to achieve consistency across our patterns, therefore it doesn't make sense for us to consume the datatables.net buttons at this point.

We are currently re-working our toolbar ([PTNFLY-1893](https://patternfly.atlassian.net/browse/PTNFLY-1893)) to achieve this desired consistency.  We will also update this example when we resolve [PTNFLY-1489](https://patternfly.atlassian.net/browse/PTNFLY-1489).

2016-10-13 16:02 UTC, closed without merging

2016-11-14 18:05 UTC, bleathem commented
@rhwood the table view branch that @dlabrecq has been working on is being proposed for a merge back to the master branch via the PR https://github.com/patternfly/patternfly/pull/530.  This PR introduces (among other things) the patternfly toolbar to the table.  Feel free to review the PR and comment, additional insight is always appreciated.

2016-11-14 20:57 UTC, rhwood commented
I see that pagination is removed. I'm dealing with data sets on the order of 15,000-65,000 items. Is there a new story on how large data sets like should be dealt with, or is pagination only temporarily removed?

2016-11-14 20:59 UTC, LHinson commented
@rhwood it's just temporarily removed... we are in the process of designing pagination now. You can check out a blog post about that here: https://blog.patternfly.org/data-view-pagination-options-conceptual-design/

We are looking to wrap up that design this sprint in hopes of being able to implement it next sprint.

2016-11-14 21:23 UTC, dlabrecq commented
Not removed, just not added to this new example. The older example is still available with pagination in the test pages.

2016-11-14 21:37 UTC, LHinson commented
Thanks for the clarification @dlabrecq. @rhwood just note we have a new design in the works.