Add aria-hidden to pficons
patternfly/patternfly-3 pull request #551
Opened 2016-12-08 22:59 UTC by jawnsy

## Description

[Bootstrap's documentation](http://getbootstrap.com/components/#glyphicons-how-to-use) has the following recommendation:

> Modern versions of assistive technologies will announce CSS generated content, as well as specific Unicode characters. To avoid unintended and confusing output in screen readers (particularly when icons are used purely for decoration), we hide them with the `aria-hidden="true"` attribute.

## Changes

This PR updates the PatternFly examples to add `aria-hidden="true"` to `<span class="pficon">` tags.

No changes were made if:

* The icon is embedded in another element with `aria-hidden="true"` (for example, buttons with font icons as labels)
* The icon has a "title" attribute (I suspect screen readers would look for these, so would not want to suppress those)

Caveats/notes:

* This was done manually, so there may be some mistakes
* I haven't run any test suite since I don't know how (yet!)
* No changes were made to JavaScript, as in the cases where icons are added dynamically
* I specifically looked for files containing `pficon` and quickly went through them one by one. I fixed similar `fa` class icons as I came across them, but did not focus on those

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [x] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2016-12-08 23:04 UTC, jawnsy commented
What do you think, @LHinson? Related to our exchange on the mailing list: https://www.redhat.com/archives/patternfly/2016-December/msg00001.html

2016-12-09 14:36 UTC, srambach commented
Using ARIA tags is new ground for me, but I'm trying to learn, so I have a couple of questions. 
- Was there a reason to focus on just the pficons and not on fa? My use of the icons really comes down to which one I need, not a semantic reason that would mean they should or shouldn't be read.
- I have not looked at all the changes, but I think some of the ones now marked as hidden are actually needed - particularly in the cards where there often are not labels on the data other than the icon.
- As part of this effort, does it make sense to ensure that the icons that should be read are also properly tagged? I'm going from this - http://fontawesome.io/accessibility/ 

@dlabrecq could you give some advice on this?

2016-12-09 14:59 UTC, jawnsy commented
@srambach Hey Sarah! Great questions.

ARIA tags are kind of a nasty hack, and accessibility expert [Heydon Pickering](https://twitter.com/heydonworks) (great person to follow on Twitter) recommends against using them, instead preferring to use semantic elements where possible (e.g. use `<button>` for a button, rather than `<a href="#" class="btn">`). ARIA tags let you override built-in behaviour (treat this link as a button) so it's sort of a tool of last resort.

> Was there a reason to focus on just the pficons and not on fa? My use of the icons really comes down to which one I need, not a semantic reason that would mean they should or shouldn't be read.

Nope, the reason I spent my lunch hour doing this was that I saw the advice from Bootstrap, and thought our examples should be, well, exemplary :wink:

I fixed up the `fa` icons whenever I came across them, but it seemed more difficult to search for (given that I was using a simple text search for `pficon`). Somebody with more JS/DOM-fu might know of a tool that can query in a more sophisticated way (return all `span` or `i` elements with classes `fa` or `pficon`), but searching for `fa` seemed like it would yield a bunch of "fa"lse positives?

> I have not looked at all the changes, but I think some of the ones now marked as hidden are actually needed - particularly in the cards where there often are not labels on the data other than the icon.

Entirely possible/likely. There were a lot of changes that I was doing manually, and very quickly as well. I'm just hoping this PR starts a discussion, and we can figure out the best approach together.

> As part of this effort, does it make sense to ensure that the icons that should be read are also properly tagged? I'm going from this - http://fontawesome.io/accessibility/

Hmm! This is a better reference than Bootstrap. Why Bootstrap doesn't just link to this page is beyond me. I tried to skip cases where we did `<span class="pficon ..." title="abc">` as I figured that might be useful for screen readers. But in cases where there's no `title`, I assumed it was just for visual styling. So I've followed somewhat loosely the recommendations there, though only by coincidence :laughing:

2016-12-09 15:08 UTC, jawnsy commented
Also, while I have no personal feelings about this, I've seen some posts [promoting SVG icons over font icons](https://twitter.com/smashingmag/status/669085272513126400), which might be something to consider for the next major version of PatternFly.

The "[Auto Accessibility](https://cdn.fontawesome.com/help#qa-autoa11y)" feature described in one of the linked pages looks pretty nifty, though we would still need to revise our examples to recommend use of the `title` tag with icons when conveying semantics is important.  It doesn't look like whatever is used to apply the transformation is open source, though, and it wouldn't work in environments that don't have access to the Internet (as is common in many enterprise deployments).

2016-12-09 15:09 UTC, dlabrecq commented
It depends if the icons are used for decoration? If the icons are purely 
visual, without any associated action, then that's not something we need 
to identify screen readers. In those cases, we simply tag the icon with 
aria-hidden="true".

The reason we hide visual styling is because it adds unnecessary clutter 
to screen readers. When navigating through a page, screen readers will 
announce every visible element in the page. Imagine how frustrating it 
can be to navigate through all that nonsense -- all that visual styling 
isn't useful to a blind user, for example.

Dan

On 12/9/16 9:36 AM, Sarah Rambacher wrote:
>
> Using ARIA tags is new ground for me, but I'm trying to learn, so I 
> have a couple of questions.
>
>   * Was there a reason to focus on just the pficons and not on fa? My
>     use of the icons really comes down to which one I need, not a
>     semantic reason that would mean they should or shouldn't be read.
>   * I have not looked at all the changes, but I think some of the ones
>     now marked as hidden are actually needed - particularly in the
>     cards where there often are not labels on the data other than the
>     icon.
>   * As part of this effort, does it make sense to ensure that the
>     icons that should be read are also properly tagged? I'm going from
>     this - http://fontawesome.io/accessibility/
>
> @dlabrecq <https://github.com/dlabrecq> could you give some advice on 
> this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/patternfly/patternfly/pull/551#issuecomment-266028016>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/AQq-alrkqB3RyfGG1Dw29DmKgxjBcgwyks5rGWeDgaJpZM4LIYhP>.
>

2016-12-13 16:57 UTC, dlabrecq requested changes
I don't know if we can make such broad changes? It's not clear if all these icons are being used purely for decoration. There may be more we need to do than just hiding the icons? For example, we may need to add some tool tips, clarify alert messages, etc.

2016-12-13 16:57 UTC, dlabrecq commented on src/js/patternfly.dataTables.pfFilter.js
> +      filter.value + '<a href="#"><span class="pficon pficon-close" aria-hidden="true"/></a></span></li>');
This is a case where adding aria-hidden=true would be an error. In this case, we should add a tool tip.

FYI, this icon is associated with an action. That is, users would select this icon to dismiss a particular filter.

2016-12-13 16:57 UTC, dlabrecq commented on tests/pages/_includes/head.html
> +      <span class="pficon pficon-warning-triangle-o" aria-hidden="true"></span>
Not certain these icons are only decoration? Unless the text describes this as a warning or error, we may need a tool tip here?

2017-01-10 17:51 UTC, bleathem commented
The approach in this PR was to  add `aria-hidden="true"` to every pf icon.  The concern raised in this PR discussion is that not _all_ icons are used purely for decoration.

@jawnsy did you evaluate whether an icon was decorative or not before applying the aria label?

2017-01-10 17:57 UTC, jawnsy commented
@bleathem I tried to, but went through really quickly so probably made a bunch of mistakes. I haven't had time to go back and look again. Maybe we should split this into smaller/less manageable chunks? WDYT, @dlabrecq?

2017-01-11 01:25 UTC, dlabrecq requested changes
There are a few errors which must to be corrected. For example, some HTML button elements are incorrectly marked hidden. For example:

&lt;button class="btn btn-link btn-find-close" type="button" aria-hidden="true">

There are other cases where icons are being used as toggle buttons (e.g., expanding list rows), which cannot be hidden. For example:

&lt;div class="list-view-pf-expand">
&lt;span class="fa fa-angle-right" aria-hidden="true">&lt;/span>

and:

&lt;span class="pficon pficon-close" aria-hidden="true">&lt;/span>

The close and arrow icons above really need title attributes, instead.

Most other icons can be marked hidden; however, this is not enough to be accessible. In many cases, a title attribute needs to be added in order for a screen reader to provide some context to the user. For example:

&lt;a href="#">&lt;span class="pficon pficon-error-circle-o" aria-hidden="true">&lt;/span>4&lt;/a>

There are two problems here:

1. We have an empty link. Screen readers will make this link available to the user, but there is no title attribute describing what this link does or where it goes.

2. There is no context as to what "4" is. Screen readers will announce the "4" all by itself, so the user has no idea what this refers to; units, number of errors, etc.?

That said, I went through all of the changes and attempted to mark everything I thought was an issue. Adding aria-hidden is a good first step, but we also need to address the missing title attributes.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/toolbar.html
> +                      <button class="btn btn-link btn-find-close" type="button" aria-hidden="true">
Close buttons should not be hidden.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/toolbar.html
> +                      <a href="#"><span class="pficon pficon-close" aria-hidden="true"></span></a>
Don't believe if this should be hidden without text or a tool tip.

The link appears to be a close action, so screen readers will expect some text describing what the link is for. Otherwise, this will be an empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/toolbar.html
> +                      <a href="#"><span class="pficon pficon-close" aria-hidden="true"></span></a>
Same as above. This will be an empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/toolbar.html
> +                      <a href="#"><span class="pficon pficon-close" aria-hidden="true"></span></a>
Same as above. This will be an empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/head.html
> +      <span class="pficon pficon-warning-triangle-o" aria-hidden="true"></span>
I'm going to say that this is probably ok considering it's an example. Although,  the description could be better here.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/cards/aggregate-status-adipiscing-mini.html
> +      <span class="card-pf-aggregate-status-notification"><span class="pficon pficon-ok" aria-hidden="true"></span></span>
There should be something (in addition to the icon) to describe the icon state. For example, adding a title here would allow screen readers to inform the user of the card's state.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/cards/aggregate-status-adipiscing.html
> +      <span class="card-pf-aggregate-status-notification"><span class="pficon pficon-ok" aria-hidden="true"></span></span>
Same as above. The outer span needs a title attribute (if the inner icon is hidden) for screen readers to convey state.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/cards/aggregate-status-amet-mini.html
> +      <span class="card-pf-aggregate-status-notification"><a href="#"><span class="pficon pficon-error-circle-o" aria-hidden="true"></span>4</a></span>
Similar to above. The href needs a title attribute for screen readers to identify what '4' is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/cards/aggregate-status-amet.html
> +      <span class="card-pf-aggregate-status-notification"><a href="#"><span class="pficon pficon-warning-triangle-o" aria-hidden="true"></span>1</a></span>
Similar to above. The href needs a title attribute for screen readers to identify what the error and warning are. Otherwise, a screen reader will simply announce "4" and "1" without any context.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/cards/dashboard-timeframe-footer.html
> +        <span class="pficon pficon-add-circle-o" aria-hidden="true"></span>Add New Cluster
The href needs a title attribute; otherwise, it's an empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/cards/object-status.html
> +        <span class="pficon pficon-screen" aria-hidden="true"></span>
The span below needs a title attribute.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards-alt.html
> +                <a href="#"><span class="card-pf-aggregate-status-notification"><span class="pficon pficon-error-circle-o" aria-hidden="true"></span>1</span></a>
The href needs a title -- empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards-alt.html
> +                <a href="#"><span class="card-pf-aggregate-status-notification"><span class="pficon pficon-error-circle-o" aria-hidden="true"></span>1</span></a>
The href needs a title -- empty link. Nothing to describe what "1" is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards.html
> +                <a href="#"><span class="card-pf-aggregate-status-notification"><span class="pficon pficon-error-circle-o" aria-hidden="true"></span>1</span></a>
The href needs title attribute -- empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards.html
> +              <a href="#"><span class="fa fa-shield" aria-hidden="true"></span><span class="card-pf-aggregate-status-count">6</span> Dolar Sit</a>
The href needs title attribute -- empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards.html
> +                <a href="#"><span class="card-pf-aggregate-status-notification"><span class="pficon pficon-error-circle-o" aria-hidden="true"></span>1</span></a>
The href needs title attribute -- empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards.html
> +              <a href="#"><span class="fa fa-shield" aria-hidden="true"></span><span class="card-pf-aggregate-status-count">199</span> Consectetur</a>
The href needs title attribute -- empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards.html
> +                <a href="#"><span class="card-pf-aggregate-status-notification"><span class="pficon pficon-error-circle-o" aria-hidden="true"></span>1</span></a>
The href needs title attribute -- empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards.html
> +                <a href="#"><span class="card-pf-aggregate-status-notification"><span class="pficon pficon-error-circle-o" aria-hidden="true"></span>1</span></a>
The href needs title attribute -- empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards.html
> +                <a href="#"><span class="card-pf-aggregate-status-notification"><span class="pficon pficon-error-circle-o" aria-hidden="true"></span>1</span></a>
The href needs title attribute -- empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/layouts/cards.html
> +                <a href="#"><span class="card-pf-aggregate-status-notification"><span class="pficon pficon-error-circle-o" aria-hidden="true"></span>23</span></a>
The href needs title attribute -- empty link.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/list-view/list-view-standard-rows-simple-expansion.html
> +        <span class="fa fa-angle-right" aria-hidden="true"></span>
Needs a title attribute. This is a toggle.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/list-view/list-view-standard-rows-simple-expansion.html
> +        <span class="pficon pficon-close" aria-hidden="true"></span>
This is a close button, which needs a title attribute.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/list-view/list-view-standard-rows-simple-expansion.html
> +        <span class="pficon pficon-close" aria-hidden="true"></span>
This is a close button, which needs a title attribute.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/list-view/list-view-standard-rows-simple-expansion.html
> +        <span class="pficon pficon-close" aria-hidden="true"></span>
This is a close button, which needs a title attribute.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/list-view/list-view-standard-rows-simple-expansion.html
> +        <span class="pficon pficon-close" aria-hidden="true"></span>
This is a close button, which needs a title attribute.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/list-view/list-view-standard-rows-simple-expansion.html
> +        <span class="pficon pficon-close" aria-hidden="true"></span>
This is a close button, which needs a title attribute.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/list-view/list-view-standard-rows-simple-expansion.html
> +        <span class="pficon pficon-close" aria-hidden="true"></span>
This is a close button, which needs a title attribute.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/secondary-nav-amet.html
>              <span>3</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/secondary-nav-amet.html
>              <span>1</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/secondary-nav-amet.html
>              <span>2</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/secondary-nav-amet.html
>              <span>5</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/tertiary-ipsum-intellegam.html
>              <span>10</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/tertiary-ipsum-intellegam.html
>              <span>4</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/tertiary-ipsum-intellegam.html
>              <span>1</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/tertiary-ipsum-intellegam.html
>              <span>3</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/tertiary-ipsum-intellegam.html
>              <span>3</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/_includes/widgets/navigation/tertiary-ipsum-intellegam.html
>              <span>1</span>
Should be a title attribute or other text describing what this is.

2017-01-11 01:25 UTC, dlabrecq commented on tests/pages/dashboard.html
> +              <a href="#"><span class="pficon pficon-refresh" aria-hidden="true"></span> Refresh Results</a>
The href needs a title attribute -- empty link.

2017-02-22 12:25 UTC, bleathem commented
> Maybe we should split this into smaller/less manageable chunks?

I agree.  I'm going to close this PR.  @jawnsy we appreciate you initiating this effort, however, as you can see, retrofitting a11y into an existing implementation is no small feat.  I would be happy to see a new PR where you introduce a subset of these changes, so we can review the approach in a more piece-wise manner.

2017-02-22 12:25 UTC, closed without merging

2017-02-22 17:08 UTC, jawnsy commented
Cool, I think smaller PRs makes sense. Or maybe just something to keep in mind for PF5?