Table view pagination
patternfly/patternfly-3 pull request #562
Opened 2017-01-04 21:15 UTC by jgiardino

## Description
Implemented CSS for the pagination row under the data table.
[PTNFLY-2074 Content Views: Pagination - CSS](https://patternfly.atlassian.net/browse/PTNFLY-2074)

## Changes

Write a list of changes the PR introduces

* Included new css in the file pagination.less
* Included a new include file pagination.html

## Link to rawgit

[Table View with Navbar](https://rawgit.com/jgiardino/patternfly/TableViewPagination-dist/dist/tests/table-view-navbar.html)
[Table View](https://rawgit.com/jgiardino/patternfly/TableViewPagination-dist/dist/tests/table-view.html)

**There's an issue** with displaying the items per page select menu in the rawgit pages because this file is not found: bootstrap-select.min.js. How do I fix this issue?

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [x] **Cross browser**: works in Chrome
- [x] **Cross browser**: works in Firefox
- [x] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [x] **Responsive**: works in extra small, small, medium and large view ports.
- [x] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2017-01-04 21:19 UTC, jgiardino commented on src/less/pagination.less
> +    width: 2.5em;
I wasn't sure what to do with this. The design has the text input width pretty small, but the width should be large enough to accommodate the width of the last page (e.g. "215" or "1008"). Should the width of this be dynamically set based on the width of the last page, or should it be arbitrarily hard-coded like it is here?

2017-01-04 21:21 UTC, jgiardino commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <ul class="pagination">
These `<ul>`s will probably need an extra class to indicate "previous" versus "next" so that we can target the correct set for disabling/enabling based on the current page.

2017-01-05 13:12 UTC, andresgalante commented on src/less/pagination.less
> +  justify-content: space-between;
PatternFly 3 supports IE9, please provide a float fallback if you are using flexbox.

2017-01-05 13:13 UTC, andresgalante commented on src/less/pagination.less
> +  border-bottom: 1px solid @table-border-color;
maybe use a margin shorthand and then remove it from the top?

2017-01-05 13:14 UTC, andresgalante commented on src/less/pagination.less
> +    width: 2.5em;
Good question, I'd hardcoded.

2017-01-05 13:17 UTC, andresgalante commented on src/less/pagination.less
> +  padding: 5px;
I'd remove this 5px, the padding on the table cell is enough IMO.

2017-01-05 13:19 UTC, andresgalante commented
@jgiardino This looks fantastic, thanks a lot! I left a few comments.

Remember that pf3 supports IE9, so if you want to use flexbox please provide a float fallback. There is an example of it on listview.

Also, to test it on IE you can use browserstack, if you have an account let me know and I'll send you an invite.

2017-01-05 13:21 UTC, andresgalante commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +  <div class="form-group">
This doesn't show:
<img width="128" alt="screen shot 2017-01-05 at 10 21 12 am" src="https://cloud.githubusercontent.com/assets/1832037/21681984/b9408620-d330-11e6-9ffb-27fc311c1fab.png">

2017-01-05 13:22 UTC, andresgalante commented
Maybe @jeff-phillips-18 or @bleathem can help with the bootstrap-select.min.js issue and raw git

2017-01-05 13:36 UTC, jeff-phillips-18 commented
@jgiardino  Add '//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js' to the url-js-extra list in both table-vew.html and table-view-navbar.html and you can remove it from the pagination.html file.

2017-01-05 14:07 UTC, jeff-phillips-18 commented
@jgiardino  Actually, looking again those table view files are includes, you need to add the change to url-js-extra to all the files that include either of them.

2017-01-05 14:49 UTC, dlabrecq requested changes
Looking good. I’m glad you didn’t try top override the DataTable pagination controls. This will actually be easier to implement.

The only change/addition I'd like to see is specific classes to help the JS plugin identify table view controls.

2017-01-05 14:49 UTC, dlabrecq commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <ul class="pagination">
Yes, having an extra class to indicate previous, next, etc. would help identify the controls for JS. When the JS plugin is created, we will need to find specific elements to attach pagination events to. This would be much easier if we had a specific class identifying each control. Otherwise, I'd have to search for 'fa-angle-double-left' or make an assumption that the first, second anchors are always previous, next, etc. which may not always be the case.

2017-01-05 14:49 UTC, dlabrecq commented on src/less/pagination.less
> +  background-color: @table-bg-accent;
I assume pagination will be used in many places other than table view, but will the generic pagination controls always have a background-color of @table-bg-accent? I'm thinking we should also have a table-view-pf-pagination class to define styles specific to the table?

I'm asking mainly because the JS plugin will need a specific selector to identify its pagination controls. The idea is to simply add a JS (plugin) file to the page and have table functionality work automatically, without providing extra setup, defining IDs, etc.

Something other than (or in addition to) content-view-pf-pagination. For example, something like table-view-pagination would help the JS differentiate the table's pagination controls from other controls that may appear in the same page.

You can see an examples with the table toolbar and empty slate. I couldn't wrap the entire table with a class because of the full page nav bar example.

2017-01-05 15:34 UTC, jgiardino commented on src/less/pagination.less
> +    width: 2.5em;
ok, I left this as-is

2017-01-05 15:35 UTC, jgiardino commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <ul class="pagination">
Except for your last comment, I think I included all the classes you would need.

2017-01-05 15:36 UTC, jgiardino commented on src/less/pagination.less
> +  justify-content: space-between;
I included css for IE9, which now looks like the example below. Please let me know if you have any suggestions about the updates I made for IE.
![screen shot 2017-01-05 at 9 58 15 am](https://cloud.githubusercontent.com/assets/21063328/21686267/c623b784-d332-11e6-9218-9ccf7c46ab43.png)

2017-01-05 15:37 UTC, jgiardino commented on src/less/pagination.less
> +  border-bottom: 1px solid @table-border-color;
I updated the border styles, assuming you were referring to border instead of margin :-)

2017-01-05 15:37 UTC, jgiardino commented on src/less/pagination.less
> +  padding: 5px;
works for me

2017-01-05 15:51 UTC, jgiardino commented on src/less/pagination.less
> +  background-color: @table-bg-accent;
I didn't see this until after I pushed my latest updates, but here are a couple of comments/questions until I get around to it...

From the examples I was looking at, it did look like pagination rows for all content views would have the same background color.  

Is it possible that there could be two tables on the same page (like in a dashboard or some two panel view)? I'm wondering if class is the best way to target the pagination controls for a specific table, or if there should be some other more specific identifier instead? Although I get your point about not requiring extra setup.

2017-01-05 16:09 UTC, jeff-phillips-18 commented
Looks like basic.html and tab.html also include table-view.html and likely need to add bootstrap-select.min.js to the url-js-extra setting.

2017-01-05 16:19 UTC, jgiardino commented
Good catch, @jeff-phillips-18! I updated those files and also included the class that @dlabrecq suggested.

2017-01-05 16:21 UTC, jeff-phillips-18 approved these changes
👍

2017-01-05 16:22 UTC, jgiardino commented
One last comment for @dlabrecq... The pagination controls are still visible when the empty state displays. I'm assuming this would be included as part of the js updates you will be working on.

2017-01-05 16:30 UTC, dlabrecq commented on src/less/pagination.less
> +  background-color: @table-bg-accent;
Yes, there can be multiple tables in the same page. Absolutely!

There may also be custom content in this area? Not only would this help the JS plugin, but it would allow the table to be more easily customized by app developers.

If you don't want to add this now, that's fine. However, I suspect I'll create something when implementing the JS plugin. I need to avoid custom IDs with the JS plugin.

2017-01-05 16:32 UTC, dlabrecq commented
I'll need to modify the JS plugin to hide the pagination controls for the empty state.

2017-01-05 16:36 UTC, dlabrecq commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <ul class="pagination">
I can search for "fa-angle-double-left", "fa-angle-left", etc. Just need something unique to grab.

2017-01-05 16:38 UTC, dlabrecq commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <ul class="pagination">
Although, having specific classes might make it easier for developers to customize the buttons? For the JS plugin to work, app developers must provide "fa-angle-double-left", "fa-angle-left", etc.

2017-01-05 17:30 UTC, andresgalante commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    of <span class="pagination-pf-pages">5</span>
There is no space between the "5" and the "of" and also with the "75"
<img width="257" alt="screen shot 2017-01-05 at 2 29 33 pm" src="https://cloud.githubusercontent.com/assets/1832037/21690515/6f30c874-d353-11e6-8bda-fd67edf7c442.png">

2017-01-05 17:31 UTC, andresgalante commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <select class="selectpicker pagination-pf-pagesize">
The shadow is too strong, isn't it?

<img width="142" alt="screen shot 2017-01-05 at 2 29 40 pm" src="https://cloud.githubusercontent.com/assets/1832037/21690546/8f5a69d4-d353-11e6-88d8-277ae16d845d.png">

2017-01-05 20:44 UTC, jgiardino commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    of <span class="pagination-pf-pages">5</span>
Oh, thanks for seeing that! Pulling out the wrapping `<span>` tags was a last minute change and I didn't even notice.

2017-01-05 20:47 UTC, jgiardino commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <select class="selectpicker pagination-pf-pagesize">
Do we apply a different shadow based on background colors? This is the shadow that's applied to .btn, but probably looks stronger due to the darker background color. Should I just remove it from this case, or lighten the opacity? Related to this, the pagination buttons have no shadow. Is that what you'd expect?

2017-01-05 21:02 UTC, andresgalante commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <select class="selectpicker pagination-pf-pagesize">
To be honest I don't know. Maybe the bootstrap select has more shadow than the dropdown. 
@kybaker Can you please take a look at this and decide if we should remove or do something with the shadow here?

2017-01-05 21:02 UTC, andresgalante commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    of <span class="pagination-pf-pages">5</span>
no problem, thanks for solving it 😄

2017-01-06 19:05 UTC, kybaker commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <select class="selectpicker pagination-pf-pagesize">
@andresgalante It should be the same as dropdown which should be the same as button. It does not matter which color it is over. A dropdown is at the same level as a button so the shadow should reflect that.

2017-01-10 15:41 UTC, jgiardino commented on tests/pages/_includes/widgets/table-view/tmpl/pagination.html
> +    <select class="selectpicker pagination-pf-pagesize">
The dropdowns are the same css-wise for select menus and buttons. The visual difference is due to the difference in backgrounds.

However, the [pagination buttons](http://www.patternfly.org/pattern-library/widgets/#pagination) currently have no shadow applied. Is that correct? Should that be fixed here or as part of another story?

2017-01-10 21:27 UTC, dlabrecq approved these changes
LGTM

2017-01-10 21:28 UTC, merged