Table View: Show/Hide Columns - PF Core
patternfly/patternfly-3 pull request #603
Opened 2017-02-20 01:57 UTC by dabeng

## Description
Adding column visibility toggle functionality for table-view. According to the design style, colvis menu should be included in the sort control group of toolbar. So if sort controls are included, then colvis menu is available. Additionally, with the help of this PR, users are allowed to identify a range that decides which columns can be toggled visibility.

## PR checklist (if relevant)
- [] works in IE9
- [] works in IE10
- [] works in IE11
- [] works in Edge
- [x] works in Chrome
- [x] works in Firefox
- [x] works in Safari
- [x] works in Opera

## Link to rawgit
https://cdn.rawgit.com/dabeng/patternfly/ColVis-dist/dist/tests/table-view-navbar.html

@LHinson @andresgalante @bleathem @jeff-phillips-18, would you like to review it ?

2017-02-20 20:30 UTC, LHinson commented
This looks good to me @dabeng!

2017-02-22 12:20 UTC, bleathem commented
I like the approach taken of using the datatables.net extension API.

@dlabrecq can you please review this PR and determine if it's consistent with our datatables.net implementation to date?

@andresgalante can you please review the CSS changes in this PR?

2017-02-22 14:30 UTC, dlabrecq requested changes

2017-02-22 14:30 UTC, dlabrecq commented on src/js/patternfly.dataTables.pfColVis.js
> +    var colVisMenu = '<ul class="dropdown-menu table-view-pf-colvis-menu">';
Thinking this HTML should be included with the toolbar layout.

2017-02-22 14:30 UTC, dlabrecq commented on tests/pages/_includes/widgets/table-view/js/config.js
> +      disabledColInx: [ 0, 6, 7 ]
I'd prefer not to use a disabled index, but provide a layouyt more like table actions and filter. That provides more customization over the control. There may be cases where a column shouldn't be shown, but devs don't have that option here.

2017-02-22 14:30 UTC, dlabrecq commented on src/js/patternfly.dataTables.pfColVis.js
> +        colVisMenu += '<li><input type="checkbox" value="' + item.idx + '" checked><label>' + item.sTitle + '</label></li>';
Prefer not to embed HTML in JavaScript. Please see the solution for action and filter options -- we should be consistent.

2017-02-23 03:36 UTC, dabeng commented
Hi @dlabrecq , I have updated the PR according your advise. Please review again 😊

2017-02-28 05:01 UTC, bleathem commented
@dlabrecq can you please review the changes @dabeng has made?

2017-02-28 13:55 UTC, dlabrecq approved these changes
LGTM

2017-02-28 13:58 UTC, merged

2017-02-28 17:21 UTC, bleathem commented
Thanks for the PR @dabeng, and thanks for the thorough review @dlabrecq