NPM Script Update & Readme
patternfly/patternfly-3 pull request #628
Opened 2017-04-13 18:39 UTC by cdcabrera

## Description

Goal, simplify install process for users unfamiliar with dev installs. Implementation of NPM scripts as aliases/shortcuts towards Grunt tasks and automated Jekyll postinstall. 

May need some review input on the "jekyll" NPM script within package.json to verify syntax. Per @bleathem removed redundant jekyll install.

## Todos
- N/A, cross browser test
- N/A, Are you sure it works on IE9?
- N/A, Is it reponsive?

## Steps to test or reproduce and link to rawgit

```sh
$ git pull https://github.com/cdcabrera/patternfly.git NPM-Scripts-4x:NPM-Scripts-4x
$ npm install
$ npm start
```

@bleathem

2017-04-25 20:37 UTC, bleathem requested changes

2017-04-25 20:37 UTC, bleathem commented on README.md
> +gem install jekyll -v 3.1.6
The preferred way to install jekyll is using `bundle install` so we all have the same dependency versions.

2017-04-25 20:37 UTC, bleathem commented on README.md
> +gem install jekyll -v 3.1.6
So +1 for the `npm run`wrapper, but the alternate command should be to use `bundle install`

2017-04-25 22:15 UTC, cdcabrera commented on README.md
> +gem install jekyll -v 3.1.6
Update applied. Looks like the rebase messed around with the review comment... should now appear as
```
gem install bundle
bundle install
```

2017-04-27 19:40 UTC, bleathem requested changes

2017-04-27 19:40 UTC, bleathem commented on package.json
> +    "jekyll": "ruby --version || echo \"Ruby required\"; gem install bundler || sudo gem install bundler; bundle install; set -e",
Let's drop the sudo part here

2017-04-27 20:37 UTC, cdcabrera commented on package.json
> +    "jekyll": "ruby --version || echo \"Ruby required\"; gem install bundler || sudo gem install bundler; bundle install; set -e",
updated

2017-05-08 21:09 UTC, bleathem approved these changes

2017-05-08 21:09 UTC, merged