Track jQuery 3 dependencies
patternfly/patternfly-3 pull request #637
Opened 2017-05-02 09:15 UTC by dabeng

## Description
All patternfly dependencies use jquery 3 APIs .

## Todos
- [ ] we need to migrate Patternfly to jQuery 3 asap if this RP merged.

## Dependencies List on gemnasium
https://gemnasium.com/github.com/dabeng/patternfly

@bleathem @priley86 , please review :)

2017-05-08 13:52 UTC, bleathem requested changes

2017-05-08 13:52 UTC, bleathem commented on bower.json
>      "jquery": "~2.1.4",
The jQuery dependency needs to be updated to jQuery 3 here.

2017-05-08 13:52 UTC, bleathem commented on package.json
>      "jquery": "~2.1.4"
The jQuery dependency needs to be updated to jQuery 3 here too.

2017-05-08 15:15 UTC, bleathem approved these changes

2017-05-08 15:16 UTC, bleathem commented
This PR looks good to me.  @dabeng I pushed some additional commits addressing the jQuery dependency itself, please review.

2017-05-08 20:57 UTC, bleathem commented
This PR looks good to me.  @dabeng please review the commits I added to your PR.

2017-05-09 00:43 UTC, dabeng commented on package.json
> +    "jquery": "~3.2.1"
@bleathem , I didn't change this line in my commit because I'm not sure the complete source code of current patternfly can work well with jquery 3. I think it will need a considerable efforts to test the compatibility.

2017-05-09 11:40 UTC, jeff-phillips-18 commented
@dabeng Could you please explain "we need to migrate Patternfly to jQuery 3 asap if this RP merged." ?

2017-05-09 11:49 UTC, jeff-phillips-18 commented on Gruntfile.js
> +          'src/js/patternfly-functions-vertical-nav.js'],
Is it worth modifying this file due to indentation?

2017-05-09 11:49 UTC, jeff-phillips-18 commented on bower.json
> +    "bootstrap-switch": "3.3.3",
Are we purposefully making this strictly 3.3.3? Is 3.3.3 required if migrating to JQuery 3?

2017-05-09 11:49 UTC, jeff-phillips-18 commented
Can we use constants for the CDN includes so that when we update versions we don't need to modify so many test pages?

2017-05-09 15:32 UTC, bleathem commented on bower.json
> +    "bootstrap-switch": "3.3.3",
As per the error introduced in this issue: https://github.com/Bttstrp/bootstrap-switch/issues/612, using the latest release brings in a jQuery 1.x dependency.

2017-05-09 15:32 UTC, bleathem commented
> Can we use constants for the CDN includes so that when we update versions we don't need to modify so many test pages?

This is a great idea, let's track that effort with a new story/PR rather than delaying this one.

2017-05-09 15:35 UTC, jeff-phillips-18 commented on bower.json
> +    "bootstrap-switch": "3.3.3",
OK, agree with the version bump, but being stringent to an exact version causes dependency conflicts for applications.

2017-05-09 17:38 UTC, bleathem commented on bower.json
> +    "bootstrap-switch": "3.3.3",
Yeah, it's unfortunate.  Can you suggest an alternate solution?  I could specify a range as in:
`"bootstrap-switch": "<=3.3.3"`

2017-05-09 17:42 UTC, jeff-phillips-18 commented on bower.json
> +    "bootstrap-switch": "3.3.3",
OK, gotcha. no good solution.

2017-05-09 17:42 UTC, jeff-phillips-18 approved these changes

2017-05-09 17:54 UTC, bleathem commented
To test this PR I ran through all test pages with the https://jquery.com/upgrade-guide/3.0/#jquery-migrate-plugin active.  The only errors I came across stemmed from application code, and I resolved them.
(cc: @dabeng)

2017-05-09 17:54 UTC, jeff-phillips-18 commented
@bleathem Could you add a link to the story/issue to use constants for CDN includes?

2017-05-09 18:53 UTC, bleathem commented
@jeff-phillips-18:
> Could you add a link to the story/issue to use constants for CDN includes?

https://patternfly.atlassian.net/browse/PTNFLY-2373

2017-05-10 01:18 UTC, dabeng commented on Gruntfile.js
> +          'src/js/patternfly-functions-vertical-nav.js'],
If don't modify indentation, grunt build will get error
`error  Expected indentation of 10 spaces but found 14  indent`

2017-05-10 22:14 UTC, bleathem commented
@dabeng can you please indicate in this PR whether you are ok with the commits I amended?

2017-05-12 13:19 UTC, merged