Merge branch 4.0 dev changes into master
patternfly/patternfly-3 pull request #650
Opened 2017-05-19 17:02 UTC by bleathem

The changes in the 4.0 dev branch are not significant enough to warrant a major version change.  This PR brings those changes into the master branch to be made available with the next PatternFly 3 minor release.

2017-05-19 17:18 UTC, dtaylor113 approved these changes

2017-05-22 15:52 UTC, jeff-phillips-18 requested changes
I think we should concatenate the functions files into patternfly-functions.js and settings files into patternfly-settings.js in order to keep backwards compatibility.

2017-05-22 15:52 UTC, jeff-phillips-18 commented on Gruntfile.js
> +          'src/js/patternfly-settings-charts.js',
I'm a bit concerned that this change now requires the inclusion of patternfly-settings.js patternfly-settings-colors.js and patterfly-settings-colors.js whereas the contents of all 3 were in patternfly-settings.js. This will break the usage if the application does not update to include the two new files as well. This change is not backwards compatible.

2017-05-22 15:52 UTC, jeff-phillips-18 commented on src/js/patternfly-functions.js
> +}(jQuery));
Breaking this out into several files will break anyone that used to simply include this file. Not backwards compatible.

2017-05-22 15:52 UTC, jeff-phillips-18 commented on src/js/patternfly-settings.js
> +})(window);
Breaking this into separate files will require inclusion of multiple file rather than just patternfly-settings.js. This is not backwards compatible.

2017-05-23 21:19 UTC, bleathem commented
Good point @jeff-phillips-18. I've re-created the patternfly-settings and patternfly-functions files at build time.  Does this address your concerns?

2017-05-24 10:45 UTC, jeff-phillips-18 approved these changes
👍

2017-05-24 14:43 UTC, dlabrecq approved these changes
LGTM

2017-05-24 14:44 UTC, merged