feat(canvas): Add Canvas and Canvas Containers
patternfly/patternfly-3 pull request #660
Opened 2017-06-02 21:57 UTC by priley86

## WIP: Canvas and Canvas Container components
Starts the HTML/CSS contribution to PF Core for the [Patternfly Canvas View](http://www.patternfly.org/pattern-library/content-views/canvas-view/)

More work is needed to be done:
* review inline canvas styles and determine if any new classes can be added 
* test selected and hover states
* add canvas toolbox 
* validate the CSS works in Angular-PF and PF-React. This LESS/CSS most closely mimics the current CSS in Angular-PF.

## Todos
- [x] cross browser test
- [ ] Are you sure it works on IE9?
- [ ] Is it responsive? 
I will need some feedback on any potential responsive states we'd like to support

## Steps to test or reproduce and link to rawgit
Canvas:
https://rawgit.com/priley86/patternfly/canvas-view-dist/dist/tests/canvas.html

Canvas Containers:
https://rawgit.com/priley86/patternfly/canvas-view-dist/dist/tests/canvas-containers.html

```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```

cc @andresgalante @dtaylor113

2017-06-26 19:57 UTC, bleathem commented
To what degree is this PR aligned with the angular-patternfly canvas?
http://www.patternfly.org/angular-patternfly/#/api/patternfly.canvas.directive:pfCanvas

2017-07-21 15:11 UTC, dlabrecq reviewed
I tried the rawgit demo on Chrome and Firefox, but nothing seems to be working. I cannot drag, the add item button does not function, zoom does not work, etc. Unfortunately, I don't see any errors in the console.

Is the intention to just add styles to Patternfly or should this test page be functional?

2017-07-21 15:23 UTC, dtaylor113 commented
> nothing seems to be working. I cannot drag, the add item button does not function, zoom does not work, etc.

I think this is just static html and less/css contribution.  I don't see any javascript files, so I don't think anything dynamic is going to happen.

2017-07-21 21:07 UTC, dlabrecq commented
Gotcha. Thanks!

2017-07-21 21:48 UTC, dlabrecq submitted a review, later dismissed
I noticed that patternfly.org has a placeholder for a canvas example. If we plan to add this, the example will need to be located under tests/pages/_includes to be imported properly.

2017-07-21 21:48 UTC, dlabrecq commented on src/img/aws.svg
> +<?xml version="1.0" encoding="utf-8"?>
Do we want to add 3rd party logos to the Patternfly repo? We already have the OpenShift logo, but that's Red Hat.

2017-08-17 02:33 UTC, priley86 commented
@dlabrecq @dtaylor113 sorry for the late response...this somehow passed my github filter while on vacation ;(

I would very much like to share CSS where possible across the repos (definitely the idea here). No JS behaviors implemented on purpose...

@dtaylor113 can you confirm if this would work in angular-pf (if sourced from core in this way)?

@dlabrecq i'm happy to swap any images we'd like. also fine w/ moving to the _includes folder. I'll update this PR to account for that soon..

2017-08-17 12:52 UTC, dtaylor113 commented
> @dtaylor113 can you confirm if this would work in angular-pf (if sourced from core in this way)?

Do you mean if the css was in pf core, would it work for angular-patternfly?   Did you change style names?

2017-08-17 13:27 UTC, priley86 commented
@dtaylor113 No class names were changed (and I attempted to mimic angular-pf as close as possible). However, I was pulling a subset of the angular-pf css at the time (so would like to ensure that these are *all* of the classes associated w/ canvas in angular-pf). Would also like to ensure that I mapped the colors/less variables correctly in `canvas.less`. https://github.com/patternfly/patternfly/pull/660/files#diff-a8e7e74153bbc764e423215a35bf592b

Now would also be a good time to add any additional CSS classes you'd like (i still see that some css is inline, however this appears to be desired when calculating widths/heights etc.). I will try to mimic this structure as closely as possible in pf-react once we are thru...

2017-08-17 13:30 UTC, priley86 commented
@dtaylor113 It seems that at the time i did this, `canvas.less` was not it's own file (and the css was in one file before `angular-patternfly.css`. Now that it is split, i'd be happy to adopt what's in [here](https://github.com/patternfly/angular-patternfly/blob/master/src/canvas-view/canvas/canvas.less) alongside the PF LESS variables i've added in this PR...

2017-08-17 14:32 UTC, dtaylor113 commented
@priley86, ok, sounds good.  In general, I'd say go with what you have here, make it as close as possible to a-pf, then we can do a follow up PR in a-pf to replace the current canvas less/css to use what's in core.
Thanks!

2017-08-21 14:03 UTC, priley86 commented
@dtaylor113 i've cross checked the less w/ a-pf. Everything should be the same now except the following:

* `.right-aligned-controls`: removed vertical-align:middle as it does not apply to block level elements
* `.canvas-editor-toolbox-container`: now uses autoprefixer here to prefix `::placeholder` styles
* `.read-only` and `.canvas-in-connection-mode`: removed `!important`. these shouldn't be necessary
`.canvas` : added a default `background-image` (canvas-dot-grid.png), background-repeat and background-size. This is for display purposes in this repo. It should easy enough to override downstream in a-pf.

@dlabrecq I've moved the templates to `pages\_includes\widgets\canvas-view`. Let me know if this works...

2017-08-29 19:33 UTC, priley86 commented
@dtaylor113 @dlabrecq anything else here?

2017-10-17 13:23 UTC, andresgalante commented on src/img/aws.svg
> +<?xml version="1.0" encoding="utf-8"?>
We can't add any logo, they are copyrighted

2017-10-17 13:46 UTC, andresgalante commented on src/less/canvas-editor.less
> +.canvas-editor-container {
Every patternfly related class has a `-pf` postfix with this format:
`block-pf-element-modifier`

2017-10-17 13:47 UTC, andresgalante commented on src/less/canvas-editor.less
> +  height: 100%;
100% of what?

2017-10-17 17:37 UTC, andresgalante commented
We'll have to rework the CSS. @LHinson this is not a simple task, you would like to create a story for it?

2017-10-17 19:19 UTC, priley86 commented on src/less/canvas-editor.less
> +.canvas-editor-container {
+1

2018-03-28 15:06 UTC, jeff-phillips-18 requested changes
Just marking as 'request changes' so as not to get merged until the CSS is reworked.

2018-06-22 13:34 UTC, LHinson commented
After talking with @priley86, we are going to close this one. If/when work picks back up, a new PR will be generated. Thanks everyone.

2018-06-22 13:34 UTC, closed without merging