ci(releasing): Add travis config and semantic-release
patternfly/patternfly-3 pull request #679
Opened 2017-07-06 04:18 UTC by dabeng

This PR introduces [semantic-release](https://github.com/semantic-release/semantic-release) for automating releases of patternfly to NPM via Travis. Semantic-releases requires a strict [commit message format](https://github.com/semantic-release/semantic-release#default-commit-message-format) which can be ensured by running npm run commit with [commitizen](https://www.npmjs.com/package/commitizen). This process ensures release automation of patternfly-react with every merge to master and proper semantic versioning at all times.

@priley86 @bleathem , please review :)

2017-07-06 13:20 UTC, priley86 requested changes
This is pretty close...just need to setup the test page bits for PF Core...

2017-07-06 13:20 UTC, priley86 commented on release.sh
> +npm run build-storybook
We will want to modify the way we do test pages here (based on existing build process in PF). React Repo is setup a bit differently and uses storybook which does not exist in PF Core.

2017-07-07 01:01 UTC, dabeng commented on release.sh
> +npm run build-storybook
you mean I should remove the line "npm run build-storybook"

2017-07-09 02:42 UTC, cdcabrera submitted a review, later dismissed

2017-07-09 02:42 UTC, cdcabrera commented on release.sh
> +npm run build-storybook
Indeed, we're going to need to remove that line @dabeng along with any following "storybook" references,  and aim for what PatternFly focuses on with its ```-dist``` branch, which can be extrapolated from the [PatternFly-Eng-Release repo](https://github.com/patternfly/patternfly-eng-release). May take a bit to pick apart.

@priley86 additional recommendations for replacements?

2017-07-09 02:42 UTC, cdcabrera commented on package.json
> +    "commit": "git-cz",
Not necessarily a big deal, but if we're replacing a Git process with a single NPM script alias maybe think about adding a ```git add .``` to this ```commit```, like:

```javascript
"commit": "git add .; git-cz"
```

2017-07-10 19:29 UTC, cdcabrera commented on package.json
> +    "commit": "git-cz",
Caught up with @priley86 on this one, ignore this comment

2017-07-12 13:25 UTC, priley86 commented
@bleathem thoughts? I'm not entirely sure yet @cdcabrera ...

2017-07-14 20:03 UTC, bleathem requested changes
We are missing the build step and commit to dist, I'll add some line comments describing where to put them.

2017-07-14 20:19 UTC, bleathem submitted a review, later dismissed
We are missing the build step and commit to dist, I added some line comments describing where to put them.

2017-07-14 20:19 UTC, bleathem commented on release.sh
> +cd .out
This is the storybook build folder, we can drop this.

2017-07-14 20:19 UTC, bleathem commented on release.sh
> +git init
We don't need this line either

2017-07-14 20:19 UTC, bleathem commented on release.sh
> +git add .
Change this to:
```
npm run grunt build
npm add . -f
```

2017-07-16 03:00 UTC, dabeng commented
@bleathem , awesome commits. I have no doubt about it :+1:

2017-07-17 17:27 UTC, priley86 commented
@bleathem can we ensure this doesn't break our current Travis build process in a dev fork? I would <3 confirmation on this...just know that a lot of folks are still relying heavily on this process.

2017-07-21 15:30 UTC, dlabrecq requested changes

2017-07-21 15:30 UTC, dlabrecq commented on .travis.yml
>    - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
We should consider removing this. I don't think this is needed anymore? We took it out of patternfly-ng because of issues with the symantic release.

2017-07-21 15:30 UTC, dlabrecq commented on scripts/release.sh
> +git push --force --quiet ssh-origin master:master-dist
We need to merge the master-dist branch. Cannot simply force push because you'll wipe out commits, tags, etc. 

Note that we're still using the patternfly-eng-release scripts to build and push to master-dist. This particular script is duplicating all that.

This looks like a script from the patternfly-react repo? They're not using patternfly-eng-release, which is fine, but there is far more that you need to handle here.

Although we don't need to release, patternfly-eng-release still build, runs tests, shrinkwrap, tests the npm and bower installs, etc. It also ensures that Travis only pushes to master-dist from the master branch. It also ensures this runs on a merge, not a pull request -- most importantly, not from someone's forked repo.

2017-07-21 15:30 UTC, dlabrecq commented on scripts/release.sh
> +git push --force --quiet ssh-origin master:master-dist
Please take a look at patternfly-ng to see how the semantic release and patternfly-eng-release are used together.

2017-07-26 09:48 UTC, dabeng commented on scripts/release.sh
> +git push --force --quiet ssh-origin master:master-dist
@dlabrecq , I need your advice about how to write option "publish-travis" in package.json file.

2017-07-26 13:03 UTC, dlabrecq commented on scripts/release.sh
> +git push --force --quiet ssh-origin master:master-dist
You can read up about how to use the publish-travis piece here: https://github.com/patternfly/patternfly-eng-publish

FYI, @bleathem wrote those instructions.

2017-07-28 00:24 UTC, bleathem commented on scripts/release.sh
> +git push --force --quiet ssh-origin master:master-dist
> We need to merge the master-dist branch. Cannot simply force push because you'll wipe out commits, tags, etc.

Force-pushing to the master-dist branch will not wipe out tags.  We will lose references to old un-tagged commits, but IMO that's an advantage, not a disadvantage.  Tagged commits (eg. releases) will persist as off-shoots from the master branch.  The master-dist branch will then exist as always 1 commit ahead of master.  If this is unclear I can create and share a graphic showing what the commit history would look like with this approach.

2017-07-28 14:31 UTC, dlabrecq commented on scripts/release.sh
> +git push --force --quiet ssh-origin master:master-dist
Force push was also my first choice, but it didn't work out as expected. I believe we're publishing from and tagging master-dist (to include the generated files), so we cannot simply wipe out its history. We need the generated files because bower installs run off of the branch tag.

Semantic releases are also based on based on commit differences. That means you cannot add a commit to push to master-dist, and then run the symantic release. It will error because the commit for the generated files is not in master.

We encountered that with patternfly-ng, so we adjusted the symantic release to run on master-dist. It may be possible to run the symantic release before pushing to master-dist, but we probably still want to include those generated files.

2017-07-31 17:48 UTC, priley86 commented on scripts/release.sh
> +git push --force --quiet ssh-origin master:master-dist
I'm fine w/ adopting the patternfly-ng approach (semantic-releases + the build scripts for automated -dist branches). Should we choose to explore Storybooks in the future, this may become moot though as we've implemented a command in the storybook-deployer for deploying test pages to gh-pages branch or a rawgit branch in a dev's fork. It may still be desired to have automated Travis builds in a dev's fork for deploying test pages, but I don't think it should be required (as a command may be less setup overhead than setting up Travis). I think supporting both options might be nice...

Thanks for providing some helpful feedback on this @dlabrecq @bleathem

2017-07-31 18:20 UTC, dlabrecq commented on scripts/release.sh
> +git push --force --quiet ssh-origin master:master-dist
Agreed. We just have to ensure master dist is merged, regardless of how we deploy test pages or whether we adopt the patternfly-ng approach.

My point is that we must include the generated files in a tagged branch. If they're added to master-dist, then that's where we must add our tags. It matters for patternfly and angular-patternfly because these repos still support bower installs.

2017-08-29 19:38 UTC, priley86 commented
@dlabrecq @dabeng @bleathem i'm guessing this PR can be closed now? We've already added semantic-releases here...

2017-08-29 23:25 UTC, dlabrecq commented
Yes, @dabeng asked me about closing this. Thought it was closed a while ago.

2017-08-29 23:25 UTC, closed without merging