App launcher
patternfly/patternfly-3 pull request #684
Opened 2017-07-17 17:30 UTC by matthewcarleton

## Description

I've updated the app launcher css to use flex box. This allows more flexibility for the list view and grid view.

This has been tested and works in all major browsers. There are some visual differences in IE9, IE 10 (windows 8) but it still functions properly.

## Todos
- [ ] cross browser test
- [ ] Are you sure it works on IE9?
- [ ] Is it reponsive?

## Steps to test or reproduce and link to rawgit
https://rawgit.com/matthewcarleton/patternfly/app-launcher-dist/dist/tests/application-launcher-nav.html.

Also, you may want to please any @mentions you'd like to review.

2017-07-19 19:54 UTC, andresgalante requested changes
The css looks great

2017-07-19 19:54 UTC, andresgalante commented on tests/pages/_includes/widgets/navigation/application-launcher.html
> +              <span class="applauncher-pf-link-title">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est deserunt praesentium aut at expedita in architecto eius ad voluptatum adipisci ulla
@matthewcarleton Let's remove this and make it a single word

2017-07-20 13:09 UTC, andresgalante approved these changes

2017-07-20 14:06 UTC, cshinn approved these changes
LGTM

2017-07-20 14:17 UTC, cdcabrera reviewed
Added an odd number of items. @matthewcarleton 
 @andresgalante Are we're expecting the odd number to span the gap? If so I'm good...   

![screen shot 2017-07-20 at 10 15 22 am](https://user-images.githubusercontent.com/3761375/28421940-9e2a528c-6d34-11e7-8bef-25452e74839e.png)

2017-07-20 14:41 UTC, andresgalante commented
@cdcabrera good catch!
@matthewcarleton Can we fix this?

2017-07-20 15:51 UTC, matthewcarleton commented
@andres @cdcabrera This is a result of flexbox. I could rebuild so the flexbox is only applied to the children for the grid.

2017-07-20 16:15 UTC, andresgalante commented
What about using grid with a flexbox fallback? Am I pushing it?

2017-07-20 17:20 UTC, matthewcarleton commented
I've updated with a nice suggestion from @andresgalante thanks!

2017-07-20 17:26 UTC, cshinn commented
Looks great @matthewcarleton!

2017-07-21 16:49 UTC, beanh66 commented
@matthewcarleton Does this work with the Vertical Nav as well or is that a separate PR? Just wanted to make sure since all the examples in rawgit are horizontal nav. Thanks!

2017-07-21 17:55 UTC, matthewcarleton commented
@beanh66 that's a great point. I think a separate PR makes more sense for it. Thanks!

2017-07-21 20:17 UTC, beanh66 commented
@matthewcarleton Okay great thanks! Just wanted to be sure this is available for both Navs 👍

2017-07-21 20:18 UTC, beanh66 approved these changes
LGTM!

2017-07-24 13:29 UTC, cdcabrera approved these changes
@matthewcarleton looks good

@andresgalante @cshinn

2017-07-24 13:33 UTC, merged