[*WIP*] Implementing showcase design changes for jQuery
patternfly/patternfly-3 pull request #703
Opened 2017-08-08 19:52 UTC by amarie401

## Description
As apart of on-going efforts to separate jQuery from PF-core, I have been working on a showcase page to host all of pf-jQuery components #692 .

I have started the process of implementing the design templates/mockups for the showcase pages based off of these two pages: 

http://rawgit.com/junezhang/showcase/master/index.html
https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html

Storybook does not currently work with jQuery. @junezhang could you please review and recommend any changes so far to what I have done? :)

## Link to rawgit and/or image
![showcase](https://user-images.githubusercontent.com/20052391/29091048-99b9cc94-7c4f-11e7-8621-1ab231006c32.gif)

2017-08-09 04:10 UTC, junezhang requested changes

2017-08-09 04:10 UTC, junezhang commented on tests/pages/jquery/index.hbs
> +              <a id="logo" title="PatternFly Showcase" href="#">PATTERNFLY-JQUERY<span class="secondary-logo"> SHOWCASE</span></a>
`<a id="logo" title="PatternFly jQuery" href="#">PATTERNFLY-<span class="secondary-logo">JQUERY</span></a>`
Here should be PatternFly-jQuery, replace the "SHOWCASE" by "JQUERY"

2017-08-09 04:10 UTC, junezhang commented on tests/pages/jquery/index.hbs
> +          </div>
Beside the github link, there is an icon for all the patternfly showcases. User can click that icon to switch to any one showcase.  
![screen shot 2017-08-09 at 11 56 19 am](https://user-images.githubusercontent.com/701009/29104666-cb7189f2-7cf9-11e7-9c9e-1520b4cbab45.png)

2017-08-09 04:10 UTC, junezhang commented on tests/pages/jquery/index.hbs
> +              </li>
Same with the above comment about the PatternFly showcase list icon.

2017-08-09 04:10 UTC, junezhang commented on tests/pages/jquery/index.hbs
> -          <h1 class="doc-title">JQuery Components</h1>
Is that "jQuery Components"?

2017-08-09 04:17 UTC, junezhang commented
Thanks for your PR. @amarie401  I left some comments in the code lines.

2017-08-09 11:42 UTC, amarie401 commented
Thank you for your comments @junezhang. I will make the changes you have requested and follow up.

2017-08-09 15:24 UTC, amarie401 commented
@junezhang I have made the requested changes. Please let me know if there is anything missing or anything that should be added. Also I am having a small issue with the dropdown icon not aligning with the nav properly, it is a bit higher than the other li items although I am using the same html & css for the nav as in the rawgit link. Any suggestions on how to fix this? 

![dropdown](https://user-images.githubusercontent.com/20052391/29129527-1a23db40-7cf5-11e7-9471-deb6f2ce1954.gif)

2017-08-10 07:15 UTC, junezhang commented
@amarie401 I'd like to help this issue. Could you give me an online link, I can debug.  Or you can tell me how to run your page, I have pulled your code, but don't know how to run it.

2017-08-10 12:18 UTC, amarie401 commented
@junezhang Make sure you have node.js installed on your computer first and do 'npm install' in the console after pulling it down, then do 'npm run jquery-dev' to run the script and it should work. I cannot currently give a rawgit link until me and Brian configure Travis to run the .hbs index file. It is not an .html file at the moment because we are using handlebar.js so it will not render as such in the dist folder.

2017-08-11 06:46 UTC, junezhang commented
@amarie401 I fixed this issue on here: https://github.com/junezhang/patternfly/commit/482894e5a08d8540a59f84c98fb900d6b1ee7d21
I don't know how to add this commit to your PR. But you can copy this piece of css code to yours.

2017-08-11 15:47 UTC, amarie401 commented
@junezhang thank you! I will also begin work on the get started page to adapt to jQuery and would appreciate your feedback when I have completed it. I will add to this PR when I have completed it and let you know.

2017-08-15 17:59 UTC, merged

2017-08-15 18:09 UTC, amarie401 commented
@bleathem @junezhang I accidentally merged into the jquery-showcase branch on PF instead of my own jquery-showcase branch when I pushed my commit. I think it should be okay since I am currently the only one working in the jquery-showcase branch on PF.

2017-08-15 18:16 UTC, amarie401 commented
@junezhang I have added the "get-started" page. It is inside of tests/pages/jquery/src/get-started.html along with the get-started.css. Can you please review? Thank you. 

![get-started](https://user-images.githubusercontent.com/20052391/29329543-341f186a-81c4-11e7-8f87-e4c66ea16c02.gif)