feat(experimental): Add Experimental Features
patternfly/patternfly-3 pull request #728
Opened 2017-08-29 00:58 UTC by mindreeper2420

## Description
This PR add the Experimental Features code that is based off of the Experimental Features designs.

This PR is connected to the patternfly-design work: https://github.com/patternfly/patternfly-design/pull/338

## Changes

* New Experimental Features component

## Image

<img width="1191" alt="screen shot 2017-08-28 at 8 41 39 pm" src="https://user-images.githubusercontent.com/4032718/29799408-64ad04ac-8c31-11e7-9108-fa38e2d0899f.png">

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [x] **Cross browser**: works in Chrome
- [x] **Cross browser**: works in Firefox
- [x] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [x] **Responsive**: works in extra small, small, medium and large view ports.
- [x] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2017-08-29 10:51 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-experimental-features.js
> +
Why is this necessary?

2017-08-29 12:54 UTC, mindreeper2420 commented on src/js/patternfly-functions-experimental-features.js
> +
@jeff-phillips-18 it is needed to fire off the jQuery for the click event on the "Got It!" button. Without it, the function does not work. It follows the pattern of other areas in PatternFly (such as vertical nav).

2017-08-29 13:15 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-experimental-features.js
> +
That is done in the tests page. This doesn't seem to be doing anything. I don't believe we want to distribute this even if it was firing the "Got It!" click.

2017-08-29 14:28 UTC, mindreeper2420 commented on src/js/patternfly-functions-experimental-features.js
> +
@jeff-phillips-18 If I remove this, then the function does not work in the test page. Would it be best to remove this for the test page?

2017-08-29 14:35 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-experimental-features.js
> +
Odd, if you remove this and the call to the function in the test page. Looks like it should work. I will pull and check it out.

2017-08-29 14:39 UTC, jeff-phillips-18 commented on tests/pages/experimental-features.html
> +{% include widgets/communication/experimental-features.html" %}
extra " at the end here.

2017-08-29 14:40 UTC, jeff-phillips-18 commented
grunt build is giving me stylelint errors:

```
src/less/experimental-features.less
 17:26  ✖  Unexpected leading zero                                 number-leading-zero                    
 17:26  ✖  Unexpected unit "s"                                     unit-whitelist                         
 18:33  ✖  Unexpected leading zero                                 number-leading-zero                    
 18:33  ✖  Unexpected unit "s"                                     unit-whitelist                         
 19:36  ✖  Unexpected leading zero                                 number-leading-zero                    
 19:36  ✖  Unexpected unit "s"                                     unit-whitelist                         
 61:5   ✖  Unexpected "vertical-align" with "position: absolute"   declaration-block-no-ignored-properties
```

2017-08-29 14:48 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-experimental-features.js
> +
It doesn't work for me either way. 😢

2017-08-29 14:50 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-experimental-features.js
> +
nevermind, it does too. I was clicking the checkbox to agree and expecting the button to enable.

2017-08-29 14:51 UTC, jeff-phillips-18 commented on src/js/patternfly-functions-experimental-features.js
> +
The 'Got it!" works for me without calling the setupExperimentalFeature function.

2017-08-29 17:19 UTC, mindreeper2420 commented on tests/pages/experimental-features.html
> +{% include widgets/communication/experimental-features.html" %}
removed in latest update

2017-08-29 17:19 UTC, mindreeper2420 commented on src/js/patternfly-functions-experimental-features.js
> +
Fixed in the latest update. The test page no longer needs the setupExperimentalFeature function.

2017-08-29 17:20 UTC, mindreeper2420 commented
@jeff-phillips-18 I've updated the PR to fix the stylelint errors, remove the function problem and also add a function for enabling/disabling the 'Activate All Experimental Features' button by checking off (or unchecking) the checkbox.

2017-08-29 17:45 UTC, jeff-phillips-18 commented on Gruntfile.js
>            ],
This change can be reverted.

2017-08-29 17:50 UTC, jeff-phillips-18 approved these changes
LGTM, once the Gruntfile change is removed.

2017-08-29 19:19 UTC, dlabrecq approved these changes
LGTM

2017-08-31 18:25 UTC, LHinson commented
@andresgalante will you review this one?

2017-09-11 14:15 UTC, andresgalante commented on src/less/experimental-features.less
> +.experimental {
Hi @mindreeper2420 all classes related to pf3 should have the structure:
`block-pf-element-modifier` Can you please add a `-pf` postfix to your classes?

2017-09-11 14:16 UTC, andresgalante commented on src/less/experimental-features.less
> +  &-border {
use a shorthand `border` for this one:
`border-bottom: 3px solid @color-pf-light-green-400;`

2017-09-11 14:16 UTC, andresgalante commented on src/less/experimental-features.less
> +      -moz-transition: ease all .3;
don't add prefixes, we have autoprefixer

2017-09-11 14:18 UTC, andresgalante commented on src/less/experimental-features.less
> +    right: 0px;
don't use units after a `0`

2017-09-11 14:34 UTC, mindreeper2420 commented
@andresgalante thanks for reviewing. All comments have been addressed.

2017-09-11 16:27 UTC, andresgalante requested changes
@mindreeper2420 let's talk about this one, I think we can find a better approach together.

2017-09-11 16:27 UTC, andresgalante commented on tests/pages/experimental-features.html
> +<script>
@jeff-phillips-18 is it ok to have the JS here?

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +    border: 3px solid @color-pf-light-green-400;
since all `experimental-pf` have a border, why do we create a `-border` class? Also border usually break layouts because of the box model, maybe you should consider an outline, a gradient or an inner shadow?

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +    height: 25px;
never set a height

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +    &-minimal {
you probably need a position relative here. The absolute positioned element should be relative to something.

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +      height: 2px;
never set a hieght

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +        visibility: hidden;
what are you hiding? would it be better to do a display none?

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +      .experimental-pf-content {
Don't do margins in %, I'd add margin bottom to elements instead of top

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +    height: 500px;
no heights please

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +      margin-top: 7%;
on pf3 we don't do margins in % and every margin is usually a multiplier of 10 (10, 20, 30, 40, etc) although sometimes it's in 5 (5, 10, 15, etc).

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +      i {
don't use type selctors, in this case select the `.fa, .pficon`

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +    border-width: 0;
border: 0; no width

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +    height: 25px;
don't do heights

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +  height: 25px;
no heights

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +  padding: 2px 0;
this is strange.

2017-09-11 16:27 UTC, andresgalante commented on src/less/experimental-features.less
> +  background-image: linear-gradient(to bottom, @color-pf-light-green-400 0, @color-pf-light-green-400 100%);
you are doing a gradient from one color to the exact same color.

2017-09-11 16:27 UTC, andresgalante commented on tests/pages/_includes/widgets/communication/experimental-features.html
> +  <div class="col-xs-12 experimental-bar-minimal">
remove `col-xs-12`

2017-09-11 16:31 UTC, jeff-phillips-18 commented on tests/pages/experimental-features.html
> +<script>
@andresgalante Yes, we use JS in the test pages frequently to help show functionality.

2017-09-12 01:25 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +  background-image: linear-gradient(to bottom, @color-pf-light-green-400 0, @color-pf-light-green-400 100%);
yup-that was a fat finger error. I've updated this is the latest update.

2017-09-12 01:25 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +  height: 25px;
removed

2017-09-12 01:25 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +    height: 25px;
removed

2017-09-12 01:25 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +    border-width: 0;
adjusted

2017-09-12 01:26 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +      i {
fixed

2017-09-12 01:26 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +    height: 500px;
removed

2017-09-12 01:26 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +      .experimental-pf-content {
fixed

2017-09-12 01:26 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +        visibility: hidden;
set to `display: none;` in the latest update

2017-09-12 01:26 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +      height: 2px;
fixed

2017-09-12 01:26 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +    &-minimal {
updated

2017-09-12 01:26 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +    height: 25px;
fixed

2017-09-12 01:27 UTC, mindreeper2420 commented on src/less/experimental-features.less
> +    border: 3px solid @color-pf-light-green-400;
I've removed the border and set as a box-shadow in the latest update. It looks the same, but functions better.

2017-09-12 01:27 UTC, mindreeper2420 commented on tests/pages/_includes/widgets/communication/experimental-features.html
> +  <div class="col-xs-12 experimental-bar-minimal">
removed

2017-09-15 11:05 UTC, andresgalante commented
Hi @LHinson @crobson @matthewcarleton The "full page" version of this pattern in implemented as a new thing. I can't stop thinking that it should be just an extension on blank state. Since it's a blankstate with the green border, green icon and green btn.

What do you think?

2017-09-15 12:25 UTC, srambach commented
@andresgalante I thought the same thing when I saw it, that it was a variation of the blank state.

2017-09-21 15:17 UTC, andresgalante commented
@srambach Can you please review this PR? I've updated it based on @mindreeper2420 branch since he is on PTO now

2017-09-21 15:17 UTC, andresgalante approved these changes

2017-09-22 20:15 UTC, jgiardino commented
@andresgalante @srambach 
Should this be something that can stand alone, and not be too closely tied to the blank slate? It seems more like something that could/should be able to wrap anything else that might be considered experimental and with two variations, one where the text spans the width, and one where it is positioned to the right.

```
<div class="experimental-pf">
  <div class="experimental-pf-bar">...</div>
  <!-- any component or blank-slate message can go here -->
</div>
```
And with the green border being applied to `.experimental-pf > *` i.e. the component it wraps, but then not to `.experimental-pf-bar`.

Also, there is a bug in smaller widths where the green bar and button will overlap due to the absolute positioning. If we instead have `.experimental-pf` as a wrapper, with `.experimental-pf-bar` as a sibling to the component that is wrapped, then we can avoid using absolute positioning.

2017-09-22 20:16 UTC, jgiardino commented on src/less/experimental-features.less
> +    position: absolute;
The absolute positioning causes a bug in smaller widths where the green bar and button will overlap the contents of the blank-slate.

2017-10-11 14:46 UTC, jgiardino commented
These updates look good to me! Thanks, @andresgalante

2017-10-12 19:25 UTC, merged