adds href to vertical nav
patternfly/patternfly-3 pull request #733
Opened 2017-08-31 13:09 UTC by matthewcarleton

## Description
This addresses the issue of vertical nav accessibility issues raised here:

https://github.com/patternfly/patternfly/issues/723#event-1226278712

https://patternfly.atlassian.net/browse/PTNFLY-2533

## Changes

This adds href="#" to all <a> tags. 

## Link to rawgit and/or image

https://rawgit.com/matthewcarleton/patternfly/vertical-nav-href-dist/dist/tests/vertical-navigation-primary-only.html

@rhamilto further testing may be required on this to ensure it meets accessibility requirements.

2017-08-31 13:40 UTC, rhamilto commented
The primary nav focus state is inconsistent with the other items on the page.

![screen shot 2017-08-31 at 9 39 06 am](https://user-images.githubusercontent.com/895728/29926071-569f61d8-8e30-11e7-95de-c6e471539329.PNG)

vs.

![screen shot 2017-08-31 at 9 39 59 am](https://user-images.githubusercontent.com/895728/29926097-662e9f10-8e30-11e7-9508-55b9943e5e07.PNG)

Presumably these should be consistent so as not to confuse the user.

2017-08-31 18:24 UTC, jeff-phillips-18 commented
I don't see the secondary navigation menus being available

2017-08-31 18:56 UTC, priley86 commented
not positive what @jeff-phillips-18 is referring, but wanted to comment specifically on the a11y standards...

The use of an `a href="#"` anchor is OK per WAVE as long as anchor text or content is specified within the link (you can see that WAVE still flags this inside our `.card-pf-aggregate-status-notification` spans which are outside the scope of this PR). This is required for all anchors and buttons. The [old standard](https://www.webaccessibility.com/best_practices.php?best_practice_id=946) disallowed this, but this is outside the scope of WCAG 2 and is no longer flagged by WAVE if link test is specified.

For the specific WAVE rule in question, see the following links which also describe ways to hide anchor text if desired (though there are several ways to do this):
https://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-refs
https://www.w3.org/TR/WCAG20-TECHS/C7.html  (shows how to use a valid `a href="#"`)

<img width="266" alt="screen shot 2017-08-31 at 2 46 18 pm" src="https://user-images.githubusercontent.com/4237045/29940192-6b0c6978-8e5c-11e7-98cc-1220a5ca8500.png">

2017-08-31 18:57 UTC, priley86 commented on src/less/vertical-nav.less
> -      outline: 0;
yes..this is correct.

2017-08-31 19:00 UTC, priley86 commented
also agree w/ @rhamilto's mention of consistency of the focus state...

2017-08-31 19:00 UTC, jeff-phillips-18 commented on tests/pages/_includes/widgets/navigation/secondary-nav-amet.html
> +    <a href="#" class="secondary-collapse-toggle-pf" data-toggle="collapse-secondary-nav"></a>
Should these just be href="" ?

2017-08-31 19:06 UTC, matthewcarleton commented on tests/pages/_includes/widgets/navigation/secondary-nav-amet.html
> +    <a href="#" class="secondary-collapse-toggle-pf" data-toggle="collapse-secondary-nav"></a>
I wasn't sure about that so I just followed bootstraps example. They use the "#"

2017-08-31 19:13 UTC, matthewcarleton commented
@jeff-phillips-18 I've updated the description with the link to the story that refers to secondary/tertiary levels.

2017-08-31 19:43 UTC, dlabrecq commented
Using an href attribute becomes an accessibility issue if the link doesn't go anywhere. A screen reader may not understand that the link is not used for navigation and attempt to bring the user to the top of the page. You may consider using href="javascript:void(0);" instead?

Also ensure the anchor contains text in its body or use a tooltip to describe what the link does.

2017-08-31 20:10 UTC, priley86 commented
@dlabrecq I don't think `javascript:void(0);` is necessary any more. I would trust this w3 standard doc as the latest guideline (see Ex:1) . Not sure if there is another a11y specialists we can consult? 
https://www.w3.org/TR/WCAG20-TECHS/C7.html

2017-08-31 20:12 UTC, jeff-phillips-18 commented
From what I've seen href="" works OK

2017-08-31 22:18 UTC, priley86 commented
So this one seems somewhat controversial across different browsers and screen readers (and has changed over time)... I read a bit further b/c we don't have consensus. The downside of adding `a href="#"` is it will get added to the history (not ideal) even though this is listed in the spec as a viable option. What's not great about `href=""` is some screen readers will mistakingly read "Empty" or potentially something else if `javascript:void(0)`. It also appears some old browsers will reload with empty hrefs.

After reading this [article](https://yuiblog.com/blog/2008/01/23/empty-links/), it seems that adding a `title` attribute alongside should aid most screen readers. Most however should be OK without `title` if there is something readible inside the anchors link text.

So I don't really know what a perfect solution looks like here and would have to defer to an expert on this. However, it seems that as long as an `href` attribute is present, it will pass a WAVE check (regardless what's inside).

2017-08-31 22:55 UTC, matthewcarleton commented
@priley86 Thanks for the research on this. I've found out essentially the same thing. It's hard to get a clear answer as to what is best practice. I think you are right about deferring to an expert here.

2017-09-01 13:27 UTC, jgiardino commented
According to [WebAIM](http://webaim.org/techniques/keyboard/):

> Note: An <a> element is only keyboard accessible when it has a non-empty href attribute. `<a>` and `<a href="">` should not be used for links.

Regarding `title` text, for a link to be keyboard accessible for sighted users, the link needs to visibly have focus and the text should be visible on focus. [Don't rely on title text for this](https://www.paciellogroup.com/blog/2013/01/using-the-html-title-attribute-updated/). (As a side note, the bootstrap tooltip widget is keyboard accessible, since it the text displays on focus.)

It does look like most of the <a> elements include text by wrapping a <span> with text, except in these cases:

```
<div class="nav-item-pf-header">
    <a href="#" class="secondary-collapse-toggle-pf" data-toggle="collapse-secondary-nav"></a>
    <span>Ipsum</span>		      
</div>
```

2017-09-01 13:39 UTC, jeff-phillips-18 commented
I believe OpenShift uses href="" a lot and it is keyboard accessible. @spadgett Am I correct here?

2017-09-01 13:53 UTC, spadgett commented
`<a href="">` is specifically for AngularJS. They have an `a` directive to handle it.

https://docs.angularjs.org/api/ng/directive/a

2017-09-01 14:09 UTC, andresgalante commented
both `<a href="">` or `<a href="#0">` works since an ID cannot start with a number. I personally like it more with something inside `<a href="#0">`

2017-09-01 14:32 UTC, spadgett commented
Any reason not to use `href="#"`?

2017-09-01 15:53 UTC, andresgalante commented
Hi @spadgett  when we use `href="#"` the browser will scroll to the top of the page when the link is clicked.

On the other hand, since `#0` is invalid, it just stays there as if the href was empty.

2017-09-01 16:01 UTC, spadgett commented
Ah I see. `<a tabindex="0" role="button">` might be sufficient if the `href` causes a problem.

2017-09-01 16:04 UTC, spadgett commented
I think you can also use `return false` from the click handling to prevent `href="#"` from going back to the top of the page. (I haven't tested, though.)

2017-09-01 16:59 UTC, andresgalante commented
I don't think we should use `tabindex`, anchors are in the tab order already. An anchor without an href is a wrong anchor. having the href empty or `#0` is the same for me, but I am against using tabindex on an achor.

2017-09-04 12:42 UTC, andresgalante requested changes

2017-09-04 12:42 UTC, andresgalante commented on src/less/vertical-nav.less
> +      // outline: 0; removing this for accessability.
Maybe consider just removing this line instead of commenting it out?

2017-09-04 12:42 UTC, andresgalante commented on tests/pages/_includes/widgets/navigation/secondary-nav-amet.html
> +    <a href="#" class="secondary-collapse-toggle-pf" data-toggle="collapse-secondary-nav"></a>
change them all to `#0` please.

2017-09-05 12:41 UTC, matthewcarleton commented
@andresgalante updated, thanks!

2017-09-05 12:42 UTC, andresgalante approved these changes

2017-09-06 12:46 UTC, merged