fix(wizard): Updates wizard to use flex box
patternfly/patternfly-3 pull request #735
Opened 2017-09-05 18:51 UTC by matthewcarleton

## Description
This changes the Wizard layout to use flex box instead of positioning. It removes the need for JS for page layout.

https://github.com/patternfly/patternfly/issues/734

## Link to rawgit and/or image

https://rawgit.com/matthewcarleton/patternfly/wizard-flexbox-dist/dist/tests/wizard.html

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2017-09-05 20:04 UTC, srambach commented on src/less/wizard.less
> +  @media (max-width: @screen-xs-min) {
Any reason not to rearrange both of these into mobile-first (min-width) media queries?

2017-09-05 21:00 UTC, srambach commented
Initialization state is very tall with buttons only halfway down - they should be at the bottom, correct?

Also, the width of the left column doesn't seem to quite line up with the current version, creating extra space that takes away from the right column. 
![image](https://user-images.githubusercontent.com/19825616/30083247-c01ae1e4-925b-11e7-898a-43d78e03c561.png)

There are lots of px measurements that break if, for example, the step names are long. But I'm guessing that's out of scope for this PR. :-/

2017-09-05 23:19 UTC, matthewcarleton commented on src/less/wizard.less
> +  @media (max-width: @screen-xs-min) {
I can actually take that altogether. That was something that I forgot to remove  :(

2017-09-05 23:25 UTC, matthewcarleton commented
@srambach fixed side column width on smaller screens. Not sure about the "Initialization state is very tall with buttons only halfway down - they should be at the bottom, correct?"

Can you provide a screenshot?

2017-09-06 13:37 UTC, srambach commented
You got me. I can't reproduce it now. I must have messed with something in the inspector that broke it.

2017-09-06 14:03 UTC, matthewcarleton commented
@srambach could it have been cached? There was positioning on the button bar that I was able to remove.

2017-09-07 11:48 UTC, jeff-phillips-18 approved these changes
Need to remove the updateWizardLayout function and references to it in tests/pages/_includes/widgets/communication/wizard.html

2017-09-07 12:29 UTC, jeff-phillips-18 reviewed
Having some troubles pulling this into Angular Patternfly. Still checking it out.

2017-09-07 12:43 UTC, jeff-phillips-18 commented on src/less/wizard.less
> +      height: 900px;
Does this need to be set? I don't think we need a default height here.

2017-09-07 12:52 UTC, jeff-phillips-18 commented
Other than the one comment (setting default height) this works really well for angular-patternfly. No more need to set margins is great! Thanks Matt!

2017-09-07 12:54 UTC, jeff-phillips-18 requested changes
Just the one required change and then the change for the test page.

2017-09-07 13:27 UTC, matthewcarleton commented on src/less/wizard.less
> +      height: 900px;
If we remove the fixed height it sets the height based on the content. That 900px was from the original implementation of the wizard.

2017-09-07 13:30 UTC, jeff-phillips-18 commented on src/less/wizard.less
> +      height: 900px;
I would let applications set the value (900px is random anyhow). If we feel strongly about leaving it in, I can adjust but to me it is pretty random and likely to be overridden by applications.

2017-09-07 13:52 UTC, jeff-phillips-18 commented on src/less/wizard.less
> +      height: 900px;
@matthewcarleton you can leave the height setting, could cause backwards compatibility issues

2017-09-07 14:05 UTC, jeff-phillips-18 approved these changes
LGTM 👍

2017-09-07 14:15 UTC, matthewcarleton commented
@jeff-phillips-18 great thanks Jeff! @srambach or @andresgalante any issues you see?

2017-09-08 19:00 UTC, jeff-phillips-18 commented
@srambach Are you OK with this now? This is necessary for the A-PF work which is required upstream.

2017-09-08 19:10 UTC, srambach commented
Yeah, I talked to @matthewcarleton and my concerns about the media queries can be done another time.

2017-09-08 19:11 UTC, merged