refactor(style(notifications): enhancement):
patternfly/patternfly-3 pull request #748
Opened 2017-09-12 17:35 UTC by sg00dwin

add border around notification icon badge to help distinguish when unread notifications are present by increasing contrast between icon and badge.

<img width="36" alt="screen shot 2017-09-12 at 12 46 34 pm" src="https://user-images.githubusercontent.com/1874151/30339807-3d43ba9e-97be-11e7-8f76-ba87e7bc68e1.png">

Related discussion https://github.com/openshift/origin-web-console/pull/1997#discussion_r136642925

2017-09-13 13:27 UTC, sg00dwin commented
@spadgett @jeff-phillips-18 @serenamarie125

2017-09-15 10:59 UTC, andresgalante requested changes

2017-09-15 10:59 UTC, andresgalante commented on src/less/navbar-vertical.less
> +        height: 12px;
Never set a height in CSS, the element might break when the text is larger

2017-09-15 10:59 UTC, andresgalante commented on src/less/navbar-vertical.less
> +        border: 2px solid @navbar-pf-vertical-bg-color;
Adding a border related to vertical nav in the bade component prevnts the badge to be used anywhere else.

If you want to make this change please add a contextual selector

2017-09-18 15:06 UTC, sg00dwin commented
@andresgalante updated the pr with a contextual class for border rule. The padding change is needed so that the badge remains a circle and not an oval.

<img width="240" alt="screen shot 2017-09-18 at 11 04 40 am" src="https://user-images.githubusercontent.com/1874151/30548859-4a1a470e-9c61-11e7-8bbb-19aa850ec23e.png">

2017-09-20 13:23 UTC, andresgalante requested changes
Also, can you please change the test pages to surface this class on the example pages?

Thanks a lot! 😄

2017-09-20 13:23 UTC, andresgalante commented on src/less/navbar-vertical.less
> +        .badge-bordered {
Hi @sg00dwin this is much better. I have 2 comments:
1. All patternfly classes are postfix with a `-pf` after the block name to know which classes come from pf and which are from bootstrap. In this case it should read `.badge-pf-bordered`
1. Can we move this class outside `.border`? if we nest them we are increasing the specificity. I don't see a reason to do it here.
Thanks a lot!

2017-09-23 01:57 UTC, sg00dwin commented
@andresgalante 
When updating the test pages I saw that the `.navbar-pf` on [nav-horizontal-notification](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/notification-drawer-horizontal-nav.html) already has a border rule, so I updated it to be consistent with `.navbar-pf-vertical` to use `.badge-pf-bordered`.

Also I went ahead an included a fix for a notification badge issue, that we came across in the OpenShift web console. pf issue #756. 

The`.fa-bell` icon would move whether the badge was displayed or not (we only show the badge if their are unread messages). Currently we are having to use absolute positioning to take .badge out of flow, this prevents it from causing the bell icon to move, when badge is shown.

I tested these changes in Chrome, Safari, FF, IE. 
Let me know what you think. 
thanks! :)

<img width="303" alt="navbar-vertical-desktop" src="https://user-images.githubusercontent.com/1874151/30769015-fb6484a4-9fde-11e7-9006-14187f903530.png">

<img width="295" alt="navbar-vertical-mobile" src="https://user-images.githubusercontent.com/1874151/30769005-d861e758-9fde-11e7-9434-35bd1dbdcae4.png">

<img width="261" alt="navbar-horizontal-badge-desktop" src="https://user-images.githubusercontent.com/1874151/30769026-1cf1ec42-9fdf-11e7-9291-9cd0e7812cf2.png">

<img width="307" alt="navbar-horizontal-badge-mobile" src="https://user-images.githubusercontent.com/1874151/30769029-2225b6da-9fdf-11e7-9757-b4f4fa2f526e.png">

----
Fixes pf issue #756

![navbar-horizonal-badge-position-absolute](https://user-images.githubusercontent.com/1874151/30769101-459f7258-9fe0-11e7-9238-8a1a8694b2dd.gif)
![badge-position-absolute](https://user-images.githubusercontent.com/1874151/30769100-459df8f6-9fe0-11e7-988b-f5402e4a78b1.gif)

2017-10-10 18:28 UTC, sg00dwin commented
@andresgalante Any updates for this?

2017-10-12 14:16 UTC, sg00dwin commented
@LHinson @spadgett @serenamarie125 
This pr fixes 2 issues we have in OpenShift
https://github.com/patternfly/patternfly/issues/756
https://github.com/openshift/origin-web-console/pull/1997#discussion_r136648077

2017-10-12 15:16 UTC, andresgalante approved these changes

2017-10-12 15:18 UTC, andresgalante commented
Sorry @sg00dwin I missed the notification.

I've asked @matthewcarleton to review it and merge it today.

thanks a lot!

2017-10-12 19:23 UTC, matthewcarleton approved these changes
LGTM thanks Steve!

2017-10-12 19:23 UTC, merged