chore(tests): Add regression test optimizations
patternfly/patternfly-3 pull request #780
Opened 2017-10-17 13:20 UTC by cliffpyles

## Description
This commit iterates on the initial regression test implementation. The changes are meant to provide a better developer experience for working with regression tests, and to prepare the code for integration with Travis.

This is an iteration for: https://patternfly.atlassian.net/browse/OSUX-171
And preparation for: https://patternfly.atlassian.net/browse/OSUX-172

## Changes

Write a list of changes the PR introduces

- Add express server for running tests, to remove need for npm start
- Add approve npm script for confirming the new reference images should be generated
- Added all viewports for all states that Bootstrap accounts for (see: https://getbootstrap.com/docs/3.3/css/#grid-media-queries)
- Optimized diff settings for better visibility
- Updated script naming
- Updated instructions for usage
- Add pdf generation for approval step
- Add npm script for cleaning up hung chrome instances
- Automatically load all scenarios
- Add a disabled feature for scenarios
- Add reference images for regressions

2017-10-17 18:54 UTC, priley86 commented
@cliffpyles nice job on this... I like the concept of being able to approve changes in our visual ui tests and auto-update them (this is very similar to how Jest does updates of Snapshot tests in React, only a different paradigm here 😸 ). I'm all for automating this process like you've done here.

2017-10-17 18:55 UTC, priley86 commented on .travis.yml
> +  - '6'
I'm not positive if this will impact other downstream projects (i.e. pf.org), but we'd need to confirm that...

2017-10-18 08:19 UTC, cliffpyles commented on .travis.yml
> +  - '6'
I haven't seen any issues with grunt plugins. I'll take a second look though. What would be the best way to find out about the impact of downstream projects?

Also – The Node LTS is currently 6 and will be 8 on the 31st of this month, and the LTS is what we support according to the README. Would that have any affect on this?

For reference this is our statement in the README:
> PatternFly stays up to date with the Node LTS Release Schedule. If you're using PatternFly downstream, we suggest the use of an actively supported version of Node/NPM, although prior versions of Node may work.

2017-10-18 10:59 UTC, jeff-phillips-18 requested changes

2017-10-18 10:59 UTC, jeff-phillips-18 commented on backstop/config/scenarios/about-modal.js
> +  url: 'http://localhost:4200/about-modal.html'
Can we put the port in a config file somewhere? Would be nice to only have to change in one place. Also, it would allow to be easily overridden if someone per chance was already using the port on their device.

2017-10-18 10:59 UTC, jeff-phillips-18 commented on README.md
> +To approve differences run: `npm run approve`
Can you explain when/if this should be done?

2017-10-18 12:52 UTC, cliffpyles commented on backstop/config/scenarios/about-modal.js
> +  url: 'http://localhost:4200/about-modal.html'
In the next PR for CI integration, I was going to implement the environment variables and command line arguments. Can the configuration file be done with those also?

2017-10-18 12:52 UTC, cliffpyles commented on README.md
> +To approve differences run: `npm run approve`
Yep.

2017-10-18 13:46 UTC, priley86 commented on .travis.yml
> +  - '6'
Yes - I seem to remember adding that bit a while ago during the Node 4 upgrade ;)
At the time pf.org had some older dependencies that weren't ready. Since then we've changed the built a lot though...

@bleathem @dlabrecq can you speak to this? Does pf.org sharing any pages impact the Node 6 upgrade here?

2017-10-18 13:54 UTC, jeff-phillips-18 commented on README.md
> +when the tests find conflicts, but the changes/conflicts are intended. This command
Should we call this approve-images or something indication what you are approving?

2017-10-18 14:04 UTC, cliffpyles commented on README.md
> +when the tests find conflicts, but the changes/conflicts are intended. This command
What about approve-regressions? or approve-conflicts?

2017-10-18 14:27 UTC, jeff-phillips-18 commented on README.md
> +when the tests find conflicts, but the changes/conflicts are intended. This command
approve-conflicts makes more sense, thanks.

2017-10-18 14:44 UTC, jeff-phillips-18 approved these changes

2017-10-18 16:55 UTC, jeff-phillips-18 commented
@bleathem @dlabrecq Do you have any concerns with bumping to Node 6 in .travis.yml?

2017-10-18 17:41 UTC, bleathem commented
+1 for updating to node 6

2017-10-18 18:20 UTC, merged