fix(accessibility): skip to content link
patternfly/patternfly-3 pull request #800
Opened 2017-10-23 12:49 UTC by matthewcarleton

## Description
This adds a skip to content link. This is most useful when skipping navigation. As you tab through the page you will see the link appear and disappear when you tab off it. 

I've added this to the navigation pages as well, which can be seen here:

https://rawgit.com/matthewcarleton/patternfly/nav-787-dist/dist/tests/horizontal-navigation.html

Note: If you are using safari you must enable tabbing in your preferences.

closes #787 

## Link to rawgit

https://rawgit.com/matthewcarleton/patternfly/nav-787-dist/dist/tests/skip-to-content.html

2017-10-23 13:17 UTC, srambach commented
On the Nav example link above, the blue outline doesn't extend completely around the skip link. Is that intended?

2017-10-23 13:24 UTC, srambach commented
I'm seeing the skiplink after the toast notifications rather than first thing on the page on the horizontal nav example above.

2017-10-23 13:34 UTC, matthewcarleton commented
@srambach good question about the toast notification. I thought it made sense to have it after, do you think it should go before? Looking at the outline issue.

2017-10-23 13:53 UTC, andresgalante commented
@matthewcarleton I think it should be before. The skip link should always be the first element in the tab index.

2017-10-23 13:54 UTC, matthewcarleton commented
@andresgalante ok, sounds good to me.

2017-10-23 14:48 UTC, dlabrecq requested changes
I was able to see the skip like on Chrome, but it doesn't show up (couldn't find it) on Firefox. Is this intended to only work on Chrome?

2017-10-23 14:50 UTC, matthewcarleton commented
@dlabrecq thanks Dan, what version/OS are you using? I've got it working in FF

2017-10-23 14:57 UTC, dlabrecq commented
I'm using FF 56.0

2017-10-23 19:17 UTC, matthewcarleton commented
@dlabrecq hmmm, I have it working on FF 58. What OS is it?

2017-10-24 13:01 UTC, andresgalante approved these changes
CSS is ok.
@dlabrecq FireFox by default only focuses on inputs and buttons. You need to go to system preferences on OSX and change your keyboard accessibility settings.

@mcarrano can you please review this one and see if the design is ok?

2017-10-24 14:33 UTC, dlabrecq approved these changes
I see it on Firefox now. Thanks, @andresgalante, I didn't have that turned on.

2017-10-24 15:25 UTC, mcarrano reviewed
I played around with this a bit and have the following design related questions/concerns:

* I'm concerned that the pop-up message appears in the upper right of the window when the user's focus is probably initially on the upper left. It would be easy to miss this I think. Should we consider changing the location of the pop-up?

* Can we change the text to say something like "Press Enter to skip to main content".  Not sure it's obvious what the action is, although I have to admit to not using keyboard navigation so I'm not the best test target.

* Is the message configurable per usage? "Skip to main content" might not be applicable in all cases so would be nice if this could be customized per usage.

It would be great to test this or get feedback from either users who regularly use tabbing and/or someone with more expertise in this area than myself. @LHinson what are your thoughts.

2017-10-24 17:24 UTC, andresgalante commented
@dlabrecq me neither 😄  I learned all of that from FF from this PR. Thanks for bringing it up

2017-10-26 14:42 UTC, mcarrano commented
@andresgalante Per your question, yes I think the pop-up should be positioned somewhere on the left. Not sure if this needs to be different for horizontal or vertical nav. I just know that the first time I saw this I missed the pop-up as that's not where my eye was focused.

Based on what you are saying, I'm fine to leave the text as is.

2017-10-26 19:33 UTC, merged