build(package): Remove extra files from the npm distribution
patternfly/patternfly-3 pull request #812
Opened 2017-10-30 14:59 UTC by cliffpyles

Currently we are distributing a bunch of extra files with our
npm package. This has inflated the size of the package being
installed, and this commit is to optimize that. More about
the solution can be read here:

https://docs.npmjs.com/files/package.json#files

To test:

- run `npm pack`
- run `tar -tf patternfly-<version>.tgz`
- verify the folder that was extracted only has the dist folder, package.json, and README.md

Related to JIRA ticket:

https://patternfly.atlassian.net/browse/OSUX-233

Related to GitHub issues:

https://github.com/patternfly/patternfly/issues/661

https://github.com/patternfly/patternfly/issues/662

## Description
Write a few sentences describing the overall goals of the pull request's commits.

(optional) Include related PRs, Issues and or Jira stories.

## Changes

Write a list of changes the PR introduces

* Change 01
* Change 02
* Change 03

## Link to rawgit and/or image

For example: Here is a [link to Alerts on rawgit](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/alerts.html)

This is an image:

![Image description](http://placehold.it/350x150)

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2017-10-30 15:12 UTC, andresgalante commented
@gregsheremeta would you mind taking a look at this PR?

Closes #662 and #661

2017-10-30 15:15 UTC, jeff-phillips-18 approved these changes

2017-10-30 20:09 UTC, dlabrecq requested changes

2017-10-30 20:09 UTC, dlabrecq commented on .gitignore
> +*.tgz
Do we have a file with the .tgz extension or was this created by your test case?

2017-10-30 20:22 UTC, dlabrecq commented
Please also run ‘npm install’ on the built repo. Not sure if tar is the equivalent, but that’s how we test via the Travis build.

2017-10-30 20:43 UTC, cliffpyles commented on .gitignore
> +*.tgz
This is created by `npm pack` when the PR is tested. I added it because it will be a common scenario when debugging npm distributions in the future.

2017-10-30 20:51 UTC, cliffpyles commented
@dlabrecq Can you elaborate? There isn't a need to install dependencies again. `tar` is a file archive utility that is built into Linux like environments.

2017-10-31 13:59 UTC, dlabrecq commented
Prior to publishing to npm, we test by installing the build. For example, run 'npm install <dir>' on your built patternfly repo. We just need to ensure the install runs without errors.

2017-10-31 14:49 UTC, cliffpyles commented
@dlabrecq The original issue is that we were including source files and not just the distribution. The only thing that changes with this PR is the files that get published. The rest of the process is the same as it was previously.

To verify what would get published if you were to do an `npm publish`, you can run `npm pack`. The tarball that is produced is what would normally be published to npm. After you have this tarball you can verify that the correct distribution files are being published. In an automated process this would occur after tests had been executed, so running `npm install` again wouldn't serve a purpose.

Read more here: https://docs.npmjs.com/cli/pack

2017-10-31 14:57 UTC, dlabrecq commented
I understand what original issue. I'm simply asking that you run an extra test. Are you refusing to do that? Why?

I'm asking because I built/installed your changes myself and saw a potential error. I'm curious if you see the same?

2017-10-31 15:05 UTC, cliffpyles commented
I'm not refusing. I'm not sure what you are asking me to do. Are you wanting me to modify the code or perform a task?

2017-10-31 15:07 UTC, cliffpyles commented
I need you to be more specific on what the issue is, how you want to resolve the issue, and why that is the resolution for resolving the issue.

2017-10-31 15:08 UTC, gregsheremeta commented
@dlabrecq what error did you see?

2017-10-31 15:08 UTC, cliffpyles commented
@dgutride @jeff-phillips-18 @bleathem Maybe there is a communication breakdown? Any thoughts?

2017-10-31 15:14 UTC, cliffpyles commented
I've run `npm install` on my local. Is that what you are asking?

![image](https://user-images.githubusercontent.com/904039/32231702-b62a6ca2-be2c-11e7-8f79-62a3c43d6c11.png)

2017-10-31 15:40 UTC, dlabrecq commented
When I ran the install, I saw this:

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

Just wanted to make sure the installed package is what we're expecting.

2017-10-31 15:49 UTC, cliffpyles commented
Got it. Thanks for your help with the PR!

2017-10-31 15:57 UTC, dlabrecq approved these changes

2017-10-31 17:42 UTC, merged

2017-11-01 16:12 UTC, gregsheremeta commented
Before:

npm pack
ll patternfly-0.0.0-semantically-released.tgz
-rw-r--r--. 1 greg greg 43079865 Nov  1 12:09 patternfly-0.0.0-semantically-released.tgz

After:
-rw-r--r--. 1 greg greg 6046439 Nov  1 12:10 patternfly-0.0.0-semantically-released.tgz