feat(login page): basic, social, SSO logins
patternfly/patternfly-3 pull request #885
Opened 2017-12-12 19:09 UTC by matthewcarleton

## Description
Updates login to show new login screens with options for basic, SSO and social accounts.

## Link to rawgit and/or image
There are slight differences with the spacing for the design but overall very close. This was to ensure a strong base that could be used to implement all the different concepts in the inVision link below.

https://redhat.invisionapp.com/share/2DE6FA656

Here are the test pages:
https://rawgit.com/matthewcarleton/patternfly/login-responsive-dist/dist/tests/login-single-sign-on.html
https://rawgit.com/matthewcarleton/patternfly/login-responsive-dist/dist/tests/login-basic.html
https://rawgit.com/matthewcarleton/patternfly/login-responsive-dist/dist/tests/login-social-account.html
https://rawgit.com/matthewcarleton/patternfly/login-responsive-dist/dist/tests/login-social-account-two-column.html

I've also updated the design doc to include branding guidelines for each logo used: 
https://github.com/patternfly/patternfly-design/pull/512
## PR checklist

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [x] **Cross browser**: works in IE11
- [x] **Cross browser**: works in Edge
- [x] **Cross browser**: works in Chrome
- [x] **Cross browser**: works in Firefox
- [x] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [x] **Responsive**: works in extra small, small, medium and large view ports.
- [x] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2017-12-12 20:18 UTC, jgiardino commented on src/less/login.less
> +    height: 36px;
bootstrap initially defines the height of `.form-control` using this:
`  height: @input-height-base; // Make inputs at least the height of their button counterpart (base line-height + padding + border)`

Should the height in this case also be based on variables? (I'm relying on Sarah to actually follow up with a suggestion on what that would actually be ;-)

2017-12-12 20:27 UTC, jgiardino commented on src/less/login.less
> +        height: 30px;
I'm curious how this would work if the translated word for "or" is longer than 30 pixels. Do you think we need to specify height and width here? When I disable it in the inspector, I don't see a change.

Also, the "or" separator is removed in the smaller width layout. Is that intentional in the design?

2017-12-12 21:13 UTC, jgiardino commented on src/less/login.less
> +        height: 30px;
Oh about that last comment, I found the responsive design example in the invision prototype. It looks like "or" was added by the visual team, so I'm curious if they would include that in the responsive layout. I really like the use of "or" because it makes it obvious that they're two different options/methods, and it might be nice to include that in the responsive layout as well.

2017-12-12 21:18 UTC, jgiardino commented
![bitmoji](https://render.bitstrips.com/v2/cpanel/3c97455d-0ce1-4ac8-82a0-601e6d6f6fd2-a07a3b9e-da41-4f2c-af4f-5c7d9c4da655-v1.png?transparent=1&palette=1&width=123)
These screens are really nice, @matthewcarleton! 

I included a couple of inline comments about fixed sizes. There are other places with fixed font sizes that I didn't comment on, but I wonder if those should use variable sizes too?

2017-12-12 22:01 UTC, mcarrano requested changes
@matthewcarleton These look great. Just a couple of questions/comments.

* I noticed that you left out the PatternFly logotype at the top of the page. Should we keep this here even though it's really a placeholder? It just gives a better sense of what the page in intended to look like.

* I had suggested that the language selector be moved from the footer to the top of the login card, See the updated design here: https://redhat.invisionapp.com/d/main/#/console/12118257/255230615/preview  It seemed off that this would be at the bottom since I'm assuming changing the language will refresh this screen with translated content.

2017-12-12 22:48 UTC, matthewcarleton commented
@mcarrano hey Matt,
Thanks for pointing that out, the logo is actually there I'm just having path issues when it gets built. I'll fix that.

I will adjust the language selection as well.

2017-12-12 22:52 UTC, matthewcarleton commented
@jgiardino thanks Jenn! Ya you caught me, I meant to go back and update with variables for that stuff and forgot. I'll adjust :)

I think I can get rid of width/height and border radius. I'm not sure why I thought that needed to be a circle. That should deal with the longer string of text flexibility.

@mcarrano what are your thoughts on keeping the "or" in the social login that @jgiardino points out above. I agree it could be useful for all layouts.

2017-12-13 15:38 UTC, mcarrano commented
@matthewcarleton @jgiardino Agree that it would be nice to consistently use the "or" separator on social login whether in desktop or mobile layout. But how to you propose that this would respond? Would the vertical separator change to horizontal? @kybaker would also be good to get your opinion.

2017-12-13 15:56 UTC, matthewcarleton commented
@kybaker @jgiardino @mcarrano something like this is what I imagine.
<img width="324" alt="screen shot 2017-12-13 at 11 56 19 am" src="https://user-images.githubusercontent.com/287880/33948207-b71a73cc-dffc-11e7-84b4-e575f3f44619.png">

2017-12-13 16:00 UTC, jgiardino commented
I always go back and replace fixed sizes with variables last. :-) I figured that's what you were doing as well

2017-12-13 16:07 UTC, mcarrano commented
Looks good to me @matthewcarleton . Just a small nit, but shouldn't this read, "Log in using a social account"?

2017-12-13 20:30 UTC, matthewcarleton commented
@mcarrano ok thanks. I went back to look at the design for the social logins and noticed now the titles have been removed altogether. Is that intentional?

2017-12-13 22:17 UTC, mcarrano commented
@yih-wang Please see @matthewcarleton 's question. Seems like there are differences in the InVision deck between the wireframes and the hi-res mockups. In this case, the specific question includes the instructional text. Was that intentionally removed?

2017-12-14 11:34 UTC, yih-wang commented
@matthewcarleton @mcarrano  We just had a meeting yesterday with Keycloak team and some minor updates had been made. I just stick notes on wireframes to clarify which places have been modified (visual design haven't been updated yet) and will keep updating the notes if further updates are made. 

Titles are not removed but have some adjustment. "Log in using your social account" has been modified to "Log in with" because IdPs buttons can also be displayed.

And we also decided to remove the "or" in the middle of the divider line. Because it can be different numbers of characters in different language. See the wireframes to find the latest design. Thanks.

2017-12-14 13:19 UTC, matthewcarleton commented
@yih-wang thanks for the update. So if the "or" is being removed is the design remaining the same or have you adjusted the spacing? Also, should it be "Log in with" OR "Log in with :"? @mcarrano what do you think?

2017-12-14 15:43 UTC, mcarrano commented
@matthewcarleton Just using "Log in with" is fine. We typically are not using semi-colons at the end of labels.

@yih-wang Thanks for adding the notes into the InVision deck. I reviewed the latest designs and left some comments. Do you know if we can expect further changes? I had thought that the designs were fairly solid, but if we are still making changes then it seems like a moving target. Based on what I saw, the basic and social login look pretty good ( but see my question about the 'More' button for social login). The identity first and social login seem to have more questions. Please do keep us up to date on any changes that you are making.

2017-12-15 02:15 UTC, junezhang commented
@mcarrano  @matthewcarleton Currently, Basic Login / SSO Login / Social Login, these three login flows almost have been lockdown. 
Our next target is Identity First & other method(Authenticator/SMS/Backup code) design review, and Mobile Re-Design.



Currently, the following design almost have been lockdown.
- Basic Login
- SSO Login
- Social Login 

Our moving target is Identity First, and the mobile design for all login.

2017-12-15 10:10 UTC, zhutaoredhat commented
Hi @matthewcarleton The webpage looks great. After we remove the "or" the padding will be a little change. it will be looks like the mockup below.
![padding](https://user-images.githubusercontent.com/13375283/34035624-973ae1f0-e1bd-11e7-9e96-f675bf511fae.png)

2017-12-15 10:38 UTC, yih-wang commented
@mcarrano Please see @junezhang 's comment to get a general view of our progress. I think most designs are already determined. But there may be great adjustment to the responsive state design. @zhutaoredhat and I will post comments here once any further update has been made.

Thanks @matthewcarleton for the great work!

2017-12-16 12:45 UTC, srambach commented on src/less/login.less
> +      //flex-basis: 45%; if two columns are required use this
I'm a little confused by this comment and the one just above - is it work in progress or does the consumer of PF have to change this if they are using two columns? Should there be a two-column variant?

2017-12-16 13:30 UTC, srambach commented on src/less/login.less
> +    height: 36px;
Bootstrap uses `@input-height-base: (@line-height-computed + (@padding-base-vertical * 2) + 2);` so you could replicate that. I'm not sure what the +2 is for though.

2017-12-16 13:38 UTC, srambach commented on src/less/login.less
> +    margin: 20px 0 10px;
Throughout there are a lot of magic numbers and I see where it's difficult to know whether to make them variables for the one time use. Some maybe would be a fraction of @grid-gutter-width? Others I'm just not sure where they are coming from, whether the design is using "standard" PF spacings as much as we have them, or diverging for this special case.

2017-12-16 13:41 UTC, srambach commented
It looks beautiful and the responsive behavior is really nice. I left a couple of comments about fixed sizes, but your code is great and easy to read! Nice job.

2017-12-18 15:23 UTC, matthewcarleton commented on src/less/login.less
> +      //flex-basis: 45%; if two columns are required use this
This is where I got stuck, the design calls for a two column break if there are more than four items but one column if there are only 4. Changing the flex-basis will get you a two column layout. I was thinking the smallest change was the best. I commented in the html that the change was available in the CSS. Although, the design has now changed so I could change this back to bootstrap grid and just leave it at that.

2017-12-18 15:25 UTC, matthewcarleton commented on src/less/login.less
> +    margin: 20px 0 10px;
ya, I don't know where the values are coming from. I didn't know if there was much value in creating variables. Are you thinking it would be good to at least use @grid-gutter-width?

2017-12-18 16:08 UTC, srambach commented on src/less/login.less
> +      //flex-basis: 45%; if two columns are required use this
What about doing another class that is a variant of the .login-pf-social-accounts-link so that the HTML can just have that class or not, and the CSS doesn't have to change?

2017-12-18 16:09 UTC, srambach commented on src/less/login.less
> +    margin: 20px 0 10px;
If that's why it's spaced that way, then yeah. Maybe the designer can tell you that?

2017-12-18 16:42 UTC, jgiardino commented on src/less/login.less
> +      //flex-basis: 45%; if two columns are required use this
I like that approach. You can default to 100% but then have an additional class that switches it to 45%.

2017-12-19 18:36 UTC, mcarrano submitted a review, later dismissed

2017-12-19 21:08 UTC, matthewcarleton commented
@srambach @jgiardino @mcarrano This PR has been updated to reflect the requested changes. Thanks for all the help reviewing @srambach & @jgiardino, @mcarrano we should be good to merge now.

2017-12-19 22:10 UTC, mcarrano commented
@matthewcarleton Thanks for all your hard work on this! @srambach and @jgiardino are you OK to merge? We'd like to make these changes available to the Keycloak team prior to shutdown. @amysueg FYI

2017-12-20 13:03 UTC, srambach commented
LGTM 👍

2017-12-26 16:02 UTC, andresgalante commented
@matthewcarleton great job! 
The name of some classes are not great and there are some things that can probably be achieved with bootstrap structures.

Let's pair code it and merge it when you are back

2017-12-27 17:11 UTC, andresgalante requested changes
@matthewcarleton overall it's great, I made a few comments and we can pair code it next week. Thera re some indentations and spaces we can fix too.

Thanks a lot!!!

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +    width: 70%;
Why do you need a `width` here?

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +      font-weight: 700px;
this doesn't exists.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +      max-width: 500px;
I don't think that the `max-width` here is needed.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +    color: @color-pf-black-600;
I wouldn't change the color here, the form should be a normal pf form.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +    font-weight: 300;
neither the font weight. If there is a need for a font weight change, it should be global in my opinion.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +  .login-pf-header {
classnames are so confusing sometimes :(

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +    display:flex;
Why are we flexing this, the normal direction of the elements are `column` anyway.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +        border: none;
The drop menu needs a focus ring, you can tab on it and open it, but since the border is none there is no visual indication.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +  .login-pf-settings {
This class name is really bad.
If the design must stay as is, then let's think of another name. something related to forms maybe... naming is impossible.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +  .login-pf-page-footer {
Can't we just use `list-inline`?
https://getbootstrap.com/docs/3.3/css/#inline

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +    justify-content: space-between;
if you only have 2 columns and they sit size by side, then I don't think there is a need to `justify-content: space-between` right?

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +      margin: ceil((@grid-gutter-width * .75)) 0;
The login page is measuring margins relative to the `@grid-gutter-width`

I see what the intention is to keep consistency. But PF3 has no variable to keep space consistency, and if a user changes the gutter this page will break.

The relationship of these 2 things is by chance and not intentional.

I recommend changing all references to the gutter and creating a new variables.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +    display: flex;
There is no need to flex this.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +  .login-pf-social-accounts {
you could use `list-unstyled` instead:
https://getbootstrap.com/docs/3.3/css/#unstyled

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +      &-double-col {
I couldn't find this on the html. Can you point me out where it's implemented please?

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +      flex-basis: 100%;
do you actually need this? a `li` should be a block level item.

2017-12-27 17:11 UTC, andresgalante commented on src/less/login.less
> +      a {
don't flex or justify content the anchor, there is no need, just do `display: block; text-align: center;`

2017-12-27 17:36 UTC, matthewcarleton commented on src/less/login.less
> +  .login-pf-page-footer {
yup :)

2017-12-27 17:36 UTC, matthewcarleton commented on src/less/login.less
> +    justify-content: space-between;
I'll change, this is left over from the last design  :(

2017-12-27 17:37 UTC, matthewcarleton commented on src/less/login.less
> +      margin: ceil((@grid-gutter-width * .75)) 0;
Ya I talked with Sarah a bit about this b/c I just had fixed values in there. I didn't use a variable at all to begin with, I wonder if we need to create one, will it be used anywhere else?

2017-12-27 17:38 UTC, matthewcarleton commented on src/less/login.less
> +  .login-pf-social-accounts {
yup :)

2017-12-27 17:40 UTC, matthewcarleton commented on src/less/login.less
> +    display: flex;
The flex is there for when there are two columns. I can remove it and add it to the double column class.

2017-12-27 17:41 UTC, matthewcarleton commented on src/less/login.less
> +      &-double-col {
This is not shown in the build but is in the design.

2017-12-27 17:44 UTC, matthewcarleton commented on src/less/login.less
> +      flex-basis: 100%;
nope

2017-12-27 17:46 UTC, matthewcarleton commented on src/less/login.less
> +      a {
Is there a reason why one is better than the other if they have the same results?

2017-12-27 17:46 UTC, matthewcarleton commented on src/less/login.less
> +      font-weight: 700px;
ugh, removed the px.

2017-12-27 17:50 UTC, matthewcarleton commented on src/less/login.less
> +    width: 70%;
ya good point, I can remove width and leave max-width

2017-12-27 17:52 UTC, matthewcarleton commented on src/less/login.less
> +      max-width: 500px;
this is just to match the design with how the grid is setup.

2017-12-27 17:52 UTC, matthewcarleton commented on src/less/login.less
> +  .login-pf-header {
Yes I would have loved to have you around when I did these, we can talk when I get back and figured out a better naming convention.

2017-12-27 17:54 UTC, matthewcarleton commented on src/less/login.less
> +    display:flex;
I did this to control the language placement. I believe the default is row isn't it?

2017-12-27 17:54 UTC, matthewcarleton commented on src/less/login.less
> +        border: none;
yup good catch.

2017-12-27 17:55 UTC, matthewcarleton commented on src/less/login.less
> +  .login-pf-settings {
:(

2017-12-27 18:22 UTC, matthewcarleton commented on src/less/login.less
> +  .login-pf-page-footer {
I think list-unstyled works better here, there are spacing issues with list-inline

2018-01-03 19:09 UTC, andresgalante submitted a review, later dismissed

2018-01-03 19:21 UTC, kybaker commented
@matthewcarleton The only feedback I have is could we reduce the size of the logo at the smallest screen size? Other than that looks good.

2018-01-03 19:36 UTC, matthewcarleton commented
@kybaker ah yes good catch, @andresgalante that's what that 70% width was for. I'll add it back in unless you can think of a better approach.

2018-01-08 23:31 UTC, matthewcarleton commented
@mcarrano this has been updated with the show/hide function. Thanks @jeff-phillips-18 for the help 👍

2018-01-09 18:31 UTC, mcarrano commented
The show/hide function looks great. Yes, thanks for your help @jeff-phillips-18 !

2018-01-12 15:24 UTC, mcarrano approved these changes
Check all of your screens are they look good to me! Ready to merge. Thanks, @matthewcarleton

2018-01-12 16:05 UTC, srambach commented
These look really good. Nice job!

2018-01-12 16:50 UTC, merged