feat(sass): Automated gem release
patternfly/patternfly-3 pull request #886
Opened 2017-12-12 20:17 UTC by skateman

I created a shell script that releases patternfly-sass as a rubygem. I'm not sure if I'm calling it on the right line in the `.travis.yml` but it seemed logical after the `npm publish`. It is necessary to have the right version set in the `package.json` and all the js/sass/font/image files in the `dist` folder.

2017-12-12 20:17 UTC, skateman commented
FYI @himdel

2017-12-12 21:14 UTC, dlabrecq requested changes

2017-12-12 21:14 UTC, dlabrecq commented on .travis.yml
> +       sh -x ./scripts/gem_release.sh;
Can you please move this after the semantic-release-post or after _release-all.sh? Want to ensure we can cleanly read the semantic release output should the build fail. Otherwise, it looks good.

2017-12-13 01:30 UTC, dlabrecq approved these changes
LGTM. Although, I have not tested this as it requires Travis to add a version number to package.json during the PatternFly release.

2017-12-13 16:38 UTC, jeff-phillips-18 approved these changes

2017-12-17 13:47 UTC, skateman commented
Can we get this in?

2017-12-17 15:05 UTC, merged