feat(wizard): embedded wizard
patternfly/patternfly-3 pull request #899
Opened 2018-01-04 21:32 UTC by matthewcarleton

## Description
This is the embedded version of the wizard. It's still in progress, I wanted to get it up so @jeff-phillips-18 can take a look at the JS required. 

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

2018-01-08 12:25 UTC, jeff-phillips-18 submitted a review, later dismissed

2018-01-15 13:55 UTC, andresgalante requested changes
Here are scroll bars and a strange gap at the bottom of the wizard. Is that intended? ![screen shot 2018-01-15 at 10 53 19 am](https://user-images.githubusercontent.com/1832037/34945543-7f844eb0-f9e2-11e7-9f98-88df299fa57d.png)

2018-01-15 13:55 UTC, andresgalante commented on src/less/wizard.less
> +    overflow: scroll;
this is generating scroll bars

2018-01-15 13:55 UTC, andresgalante commented on src/less/wizard.less
> +    padding:0;
please add a space after the `:` we need a formatter!

2018-01-15 14:00 UTC, matthewcarleton commented on src/less/wizard.less
> +    padding:0;
:)

2018-01-15 14:00 UTC, matthewcarleton commented on src/less/wizard.less
> +    overflow: scroll;
Are you referring to the padding on the body? That is on all the test pages.

2018-01-15 14:03 UTC, andresgalante commented on src/less/wizard.less
> +    overflow: scroll;
I am referring to the scroll bars, they are always on, even though there is not content to scroll.

2018-01-15 14:07 UTC, matthewcarleton commented on src/less/wizard.less
> +    overflow: scroll;
No I mean the gap comment

2018-01-15 15:02 UTC, matthewcarleton commented
@andresgalante I think the scrolling issue is fixed now. I've added an extension for Chrome to show them and I don't see them now with overflow:auto. Can you confirm?

2018-02-06 18:38 UTC, LHinson commented
Based on our meeting with Mary, sounds like this not a requirement at this time and no reason to implement given the limitations it has re: flexibility.

2018-02-06 18:38 UTC, closed without merging