fix(secondary-tabs): refactor the secondary tabs into nested structure
patternfly/patternfly-3 pull request #906
Opened 2018-01-11 10:07 UTC by dabeng

## Description
This PR is targeted to fix [issue](https://github.com/patternfly/patternfly/issues/905).

## Changes
Users can toggle different secondary tabs 

## Link to rawgit and/or image

Examples: [Tabs](https://rawgit.com/dabeng/patternfly/sec-tabs-dist/dist/tests/tabs.html) under Widgets section, [Tab](https://rawgit.com/dabeng/patternfly/sec-tabs-dist/dist/tests/tab.html) under Layout section

2018-01-11 13:33 UTC, jeff-phillips-18 requested changes

2018-01-11 13:33 UTC, jeff-phillips-18 commented on src/less/tabs.less
> +    font-size: @font-size-base;
This would break existing consumers. The `tab-pane` class would need to be added to the parent of all existing `nav-tabs-pf` instances.

2018-01-11 22:58 UTC, jgiardino commented on src/less/tabs.less
> +    font-size: @font-size-base;
I agree with @jeff-phillips-18. We should only update the css files for this issue. The updates we make to core should not require changes to the html that is currently defined, because we don't want to break current implementations that use that html structure.

The main issue with the current css is this selector `.nav-tabs+.nav-tabs-pf` because it requires a very specific html structure that we can't reproduce in react.

To fix this, we should keep this selector `.nav-tabs+.nav-tabs-pf` so that we don't break current implementations, but also include an additional class-based selector that will apply the same styles `font-size: @font-size-base;`.  See another comment further down with specific suggestions on this change...

Then to fix this issue in the react Tabs component, add a class `nav-tabs-pf-secondary` to the react Tabs component so that the runtime html of [your storybook](https://rawgit.com/dabeng/patternfly-react/tabs-s/.out/index.html?knob-Secondary%20Tabs%20Justified=false&knob-Justified=false&knob-Tab%203%20Disabled=false&knob-Tab%202%20Disabled=false&knob-Tab%201%20Disabled=false&knob-Navigation%20Style=tabs&knob-Label=Danger%20Will%20Robinson%21&knob-Tab%203%20Tittle=Tab%203&knob-Tab%202%20Tittle=Tab%202&knob-Tab%201%20Tittle=Tab%201&selectedKind=Tabs&selectedStory=Secondary%20Tabs&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) resembles this:
```
...
<div id="secondary-tabs-1">
  <ul role="tablist" class="nav nav-tabs nav-tabs-pf nav-tabs-pf-secondary">
...
```

2018-01-11 22:59 UTC, jgiardino commented on src/less/tabs.less
> -  + .nav-tabs-pf {
... and then following up to my previous comment, you should be able to change the following selector:
`+ nav-tabs-pf`
to this:
`+ .nav-tabs-pf, .nav-tabs-pf-secondary`

But please make similar updates in the .scss file, and then please test that they actually work. 

Thanks for making this update!

2018-01-12 06:12 UTC, dabeng commented
Hi @jeff-phillips-18 , the following picture demonstrates what the PR has done.
<img width="638" alt="screen shot 2018-01-12 at 1 31 16 pm" src="https://user-images.githubusercontent.com/5689075/34861538-83093490-f7a0-11e7-89a6-b9c5e9ab384b.png">

IMO, the top one confuses users because secondary tabs don't make any response when toggling primary tabs. However, I saw the many application cases of the bottom one. I remember that there are lots of such nested secondary tabs in Errata when I contributed front-end code to it.

2018-01-12 06:35 UTC, dabeng commented on src/less/tabs.less
> -  + .nav-tabs-pf {
Thanks a lot for your lighter solution. While, I found that this solution can not work in secondary tabs of patternfly-react because the writing `+ .nav-tabs-pf, .nav-tabs-pf-secondary` will produce the following css settings:
```css
.nav-tabs .nav-tabs-pf-secondary, .nav-tabs+.nav-tabs-pf {
    font-size: 12px;
}
```

2018-01-12 06:53 UTC, dabeng commented on src/less/tabs.less
> -  + .nav-tabs-pf {
In patternfly-react secondary tabs, I need the following css settings:
```css
.nav-tabs-pf.nav-tabs-pf-secondary {
    font-size: 12px;
}
```
or
```css
.tab-pane .nav-tabs-pf-secondary {
    font-size: 12px;
}
```
or
```css
.tab-pane .nav-tabs-pf.nav-tabs-pf-secondary {
    font-size: 12px;
}
```
Sorry @jgiardino , I'm a js programmer and not good at Less, Sass, css style priority 😞. Could you provide another solution 😊

2018-01-12 06:55 UTC, dabeng commented
In patternfly-react secondary tabs, I need the following css settings:
```css
.nav-tabs-pf.nav-tabs-pf-secondary {
    font-size: 12px;
}
```
or
```css
.tab-pane .nav-tabs-pf-secondary {
    font-size: 12px;
}
```
or
```css
.tab-pane .nav-tabs-pf.nav-tabs-pf-secondary {
    font-size: 12px;
}
```
Sorry @jgiardino , I'm a JS programmer and not good at Less, Sass, css style priority 😞. Could you provide another solution. Thanks in advance 😊

2018-01-12 20:29 UTC, jgiardino commented on src/less/tabs.less
> -  + .nav-tabs-pf {
Thanks for pointing that out, @dabeng! You're right. 

I played around with the css locally, and this is what I had to do to get it to work (in the .scss version)...

In the following structure:
```
.nav-tabs {
  ...
  + nav-tabs-pf {
    ...
  }
}
```
Remove the selector `+ nav-tabs-pf` and it's styles so that it isn't nested inside `.nav-tabs`. Move this selector to a separate block. This will require that you change `+ nav-tabs-pf` to `.nav-tabs + nav-tabs-pf`, but you will also add the `.nav-tabs-pf-secondary` class to this selector, so that you end up with something like this: 
```
.nav-tabs {
...
}
.nav-tabs + .nav-tabs-pf, .nav-tabs-pf.nav-tabs-pf-secondary {
  font-size: $font-size-base;
  > li:first-child > a {
    padding-left: 15px;
    &:before {
      left: 15px !important;
    }
  }
}
```
This solution maintains both selectors—the original selector for supporting the original patternfly core solution and the new selector for supporting the patternfly-react solution. This will result in runtime css that looks like this:
```
.nav-tabs + .nav-tabs-pf, .nav-tabs-pf.nav-tabs-pf-secondary {
    font-size: 12px;
}
```

2018-01-12 20:38 UTC, jgiardino commented
Hi @dabeng,

I responded to your question with an inline comment. Hopefully this makes sense :-)

However, there has been discussion with @mcarrano on Slack regarding what the expected interaction should be with secondary tabs. We'd like to get input from @kybaker on this one before moving forward, so that we can confirm if our expectations for how this component works actually match the original intended design for the component.

2018-01-15 03:56 UTC, dabeng commented on src/less/tabs.less
> -  + .nav-tabs-pf {
Awesome 👍 Appreciated 😊

2018-01-15 04:07 UTC, dabeng commented
Hi @jgiardino , I have updated css files according to new comments.

2018-01-15 11:39 UTC, jeff-phillips-18 commented
@dabeng Could you add to the existing tabs test page or create a new secondary-tabs test page?

2018-01-15 14:32 UTC, jgiardino commented on src/less/tabs.less
> -  + .nav-tabs-pf {
@dabeng, I'm so sorry. I made a mistake in my original comment. I often will pull selectors out of a nested structure to make sure I get the right selectors, and then put them back in the nested structure if possible. But this time I forgot to put the selectors back into the nested structure.

We still want the following structure:
```
.nav-tabs {
  ...
  + nav-tabs-pf {
    ...
  }
}
```
But to get the selectors we need for the secondary tabs, we would modify it like this: 
```
.nav-tabs {
  ...
  + nav-tabs-pf, &.nav-tabs-pf-secondary {
    ...
  }
}
```

2018-01-15 18:48 UTC, jgiardino commented
@dabeng I made a correction to my previous inline comments.

Also, please move forward with finalizing the updates as we have discussed. I met with @kybaker and @mcarrano to discuss the expected interaction of the examples labeled ".nav-tabs + .nav-tabs-pf" on the [Tabs test page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/tabs.html). They agree that it is possible that designers would want to have the secondary tabs nested inside the tab panel for the primary nav. They have also requested that the updates we make to the css will continue to support the original html implementation. This is inline with the latest updates you have been making.

2018-01-16 04:57 UTC, dabeng commented
@jgiardino @jeff-phillips-18 , please review the “.nav-tabs.nav-tabs-pf-secondary” example on the [tabs test page](https://rawgit.com/dabeng/patternfly/sec-tabs-dist/dist/tests/tabs.html)

2018-01-16 12:16 UTC, jeff-phillips-18 submitted a review, later dismissed

2018-01-16 14:38 UTC, jgiardino commented
@dabeng I like that you include an example showing the alternate html structure that is now possible. However, I have a concern regarding the js and interaction for this example.

The interaction you have for the [react tabs component](https://rawgit.com/dabeng/patternfly-react/tabs-s/.out/index.html?knob-Secondary%20Tabs%20Justified=false&knob-Justified=false&knob-Tab%203%20Disabled=false&knob-Tab%202%20Disabled=false&knob-Tab%201%20Disabled=false&knob-Navigation%20Style=tabs&knob-Label=Danger%20Will%20Robinson%21&knob-Tab%203%20Tittle=Tab%203&knob-Tab%202%20Tittle=Tab%202&knob-Tab%201%20Tittle=Tab%201&selectedKind=Tabs&selectedStory=Secondary%20Tabs&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) works the way I expect it to.

The interaction of the new example labeled **.nav-tabs.nav-tabs-pf-secondary** is inconsistent in interaction—when I click the nth primary tab, the nth secondary tab is also selected. This example is potentially confusing to developers/designers who are only looking at this example, especially due to the lack of design documentation. 

My recommendation would be to remove the JS from this example, and just use it as an example of possible html structure. When I check the other tab examples, none of them have JS either.

@andresgalante @jeff-phillips-18 Do you have thoughts on this?

2018-01-16 15:06 UTC, mcarrano commented
I agree with this concern @jgiardino . When I click to a new primary tab, I would expect that the secondary tabs will change but the first one will always be selected by default.

2018-01-16 18:44 UTC, jeff-phillips-18 commented
@dabeng I like having the interaction work correctly. Can you update such that the first of the secondary tabs is active by default?

Would also be nice to use `href="javascript:void(0);` rather than `href="#"` so the page does not jump to the top when click on the tabs.

2018-01-16 19:35 UTC, jgiardino commented
Ignore this comment from me above:
> ~~My recommendation would be to remove the JS from this example, and just use it as an example of possible html structure. When I check the other tab examples, none of them have JS either.~~

I'm fine with keeping the JS and interaction, as long as you fix the issues as @jeff-phillips-18 suggests.

2018-01-17 04:01 UTC, dabeng commented
yep, I updated it again : ) @jeff-phillips-18 @jgiardino @mcarrano

2018-01-17 12:02 UTC, jeff-phillips-18 commented
@dabeng Looking better. Though I am now second guessing myself. I don't see a reason for this version of tabs to have interaction (making the primary tab active on click) whereas none of the others not the secondary tabs have the same interaction. I'm ok with leaving it though.

Could you update the rest of the tabs on this page to use `href="javascript:void(0);` rather than `href="#"` as well? It is really annoying when it scrolls to top on click.

2018-01-17 13:42 UTC, dabeng commented
OK , no problem.

2018-01-18 11:29 UTC, jeff-phillips-18 approved these changes

2018-01-22 14:47 UTC, jgiardino commented
The styling looks good to me. I'll defer to @mcarrano and @jeff-phillips-18 regarding the interaction.

2018-01-22 16:57 UTC, mcarrano commented
Yes, this looks right to me now, @jgiardino . Thanks, @dabeng

2018-01-22 17:05 UTC, merged