chore(donut chart): Donut chart default color pattern has only 2 colors
patternfly/patternfly-3 pull request #916
Opened 2018-01-18 07:43 UTC by dabeng

## Description
This PR is targeted to fix the issue #902

## Changes

Add more default colors for donut chart. 

## Link to rawgit and/or image

Here's the [demo](https://rawgit.com/dabeng/patternfly/u-d-chart-dist/dist/tests/donut-charts.html)

2018-01-18 11:25 UTC, jeff-phillips-18 requested changes

2018-01-18 11:25 UTC, jeff-phillips-18 commented on src/js/patternfly-settings-charts.js
> -            patternfly.pfPaletteColors.black300
As I mentioned in https://github.com/patternfly/patternfly/issues/902#issuecomment-358050813, we cannot change the first two colors returned by getDefaultDonutColors  or from a call to getDefaultDonutConfig because it would break existing consumers. 

We should, as the conversations in https://github.com/patternfly/patternfly/issues/902 concluded, have two donut color configs, one default (current used for utilization charts) and one for relationship donut charts.

I would suggest adding methods  getDefaultRelationshipDonutColors and getDefaultRelationshipDonutConfig to allow consumers to retrieve defaults for the relationship donut charts.

2018-01-19 03:23 UTC, dabeng commented
OK, got it

2018-01-19 11:32 UTC, jeff-phillips-18 approved these changes

2018-01-19 15:27 UTC, amarie401 approved these changes

2018-01-19 15:40 UTC, merged