feat(tree-list-view): add tree list view
patternfly/patternfly-3 pull request #980
Opened 2018-03-07 07:32 UTC by dabeng

## Description
This PR is targeted to fix issue #950.

@cliffpyles @beanh66 @matthewcarleton  @michael-coker  Please review this PR.

## Link to rawgit and/or image

- [Tree List View - Single Child Expansion](https://rawgit.com/dabeng/patternfly/tree-list-view-dist/dist/tests/tree-list-view-single-child-expansion.html)
- [Tree List View - Multiple Child Expansion](https://rawgit.com/dabeng/patternfly/tree-list-view-dist/dist/tests/tree-list-view-multiple-child-expansion.html)

2018-03-07 14:55 UTC, mcoker approved these changes
LGTM!

2018-03-08 13:10 UTC, matthewcarleton commented on src/less/tree-list-view.less
> +      z-index: auto;
Why are declaring z-index:auto; here? there is a z-index:2; on the .list-group-item.active class. Am I missing something?

2018-03-08 16:35 UTC, jeff-phillips-18 commented on src/less/tree-list-view.less
> +      color: currentColor !important;
why !important?

2018-03-08 17:00 UTC, beanh66 commented
@dabeng LGTM!

2018-03-08 17:14 UTC, jeff-phillips-18 requested changes

2018-03-08 17:14 UTC, jeff-phillips-18 commented on tests/pages/_includes/widgets/tree-list-view/tree-list-view-rows.html
> +      $(this).children('.list-group-item-header').css('padding-left', indent);
This works for the test page, but all consumers would need to do the same. Seems to me it would be beneficial to use some html or css to indent the children a specified amount (and 85px seems a bit much, likely horrid at mobile).

2018-03-09 02:22 UTC, dabeng commented on src/less/tree-list-view.less
> +      z-index: auto;
Hi @matthewcarleton ， `z-index: 2;` will cause that active list-group-item covers the bottom division line.
<img width="428" alt="screen shot 2018-03-09 at 10 14 56 am" src="https://user-images.githubusercontent.com/5689075/37187090-b7a312c0-2383-11e8-82f5-d2b330d6cd9e.png">

2018-03-09 02:28 UTC, dabeng commented on src/less/tree-list-view.less
> +      color: currentColor !important;
yes. you are right. It's not necessary.

2018-03-09 02:36 UTC, matthewcarleton commented on src/less/tree-list-view.less
> +      z-index: auto;
👍

2018-03-09 02:43 UTC, matthewcarleton commented on src/less/tree-list-view.less
> +        color: currentColor !important;
can this !important be removed as well?

2018-03-09 03:01 UTC, dabeng commented on src/less/tree-list-view.less
> +        color: currentColor !important;
yes. you are right. it could be removed too.

2018-03-09 05:00 UTC, dabeng commented on tests/pages/_includes/widgets/tree-list-view/tree-list-view-rows.html
> +      $(this).children('.list-group-item-header').css('padding-left', indent);
Yes @jeff-phillips-18 You are right. CSS solution should be the priority solution for setting indentation of child rows of tree-list-view. In fact, I also did the **[test](https://rawgit.com/dabeng/patternfly/tree-list-view-css-dist/dist/tests/tree-list-view-multiple-child-expansion.html)**, but finally I found this demo page can not fulfill the needs described on the design doc.

2018-03-09 05:04 UTC, dabeng commented on tests/pages/_includes/widgets/tree-list-view/tree-list-view-rows.html
> +      $(this).children('.list-group-item-header').css('padding-left', indent);
Finally, I followed the idea of [TreeGrid Table](https://github.com/patternfly/patternfly/blob/master/src/js/patternfly-functions-tree-grid.js#L68)  to set indentation according to nested depth with js code.

2018-03-09 16:08 UTC, dabeng commented
@jeff-phillips-18 CSS solution should be the priority solution for setting indentation of child rows of tree-list-view. In fact, I also did the **[test](https://rawgit.com/dabeng/patternfly/tree-list-view-css-dist/dist/tests/tree-list-view-multiple-child-expansion.html)**, but I found this demo page can not fulfill the needs described on the design doc.
Finally, I followed the idea of [TreeGrid Table](https://github.com/patternfly/patternfly/blob/master/src/js/patternfly-functions-tree-grid.js#L68)  to set indentation according to nested depth with js code.

2018-03-09 19:56 UTC, jeff-phillips-18 commented
The JS solution does not help adopters. They will not get this JS and would need to dig to find it. I believe there is an HTML/CSS solution that could be done here. Maybe there's an issue trying to have the border between child rows extend to the far left edge but I think it would be better to not extend and have a usable solution.

2018-03-12 02:50 UTC, dabeng commented
@jeff-phillips-18 I have removed the hard coding of setting indentation with js code. Please review the updated demo page:
- [Tree List View - Single Child Expansion](https://rawgit.com/dabeng/patternfly/tree-list-view-dist/dist/tests/tree-list-view-single-child-expansion.html)
- [Tree List View - Multiple Child Expansion](https://rawgit.com/dabeng/patternfly/tree-list-view-dist/dist/tests/tree-list-view-multiple-child-expansion.html)

2018-03-19 12:26 UTC, jeff-phillips-18 approved these changes

2018-03-19 19:33 UTC, merged